"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");
const zlib = require("zlib");

const ROOT = path.resolve(__dirname, "..", "..");
const OUT = path.join(ROOT, ".claude/window1_live_v4_replay/v34_w1_causal_capture_measurement_20260805");
const read = (name) => JSON.parse(fs.readFileSync(path.join(OUT, name), "utf8"));
const rows = (name) => zlib.gunzipSync(fs.readFileSync(path.join(OUT, name))).toString("utf8").trim().split(/\r?\n/).filter(Boolean).map(JSON.parse);

const control = read("CONTROL_BINDING.json");
const start = read("START_LEDGER_V3_IDENTITY_AND_EDGE_RECEIPT.json");
const spans = read("WINDOW1_SPAN_804.json");
const edge = read("HARD_RIGHT_EDGE_RECEIPT.json");
const score = read("SCORECARD_TWO_COLUMN.json");
const strictFrontier = read("STRICT_FRONTIER.json");
const censusFrontier = read("CENSUS_PRICED_FRONTIER.json");
const strictRegret = read("STRICT_REGRET_GAUGE.json");
const censusRegret = read("CENSUS_PRICED_REGRET_GAUGE.json");
const isolation = read("CLOSE_TELEMETRY_ISOLATION_RECEIPT.json");
const trace = read("DECISION_TRACE_CONSERVATION.json");
const r3 = read("R3_SAME_WINDOW_COMPARISON.json");
const offer = read("UNDER_PAR_OFFER_BINDING.json");
const forbidden = read("FORBIDDEN_ACCESS_RECEIPT.json");
const determinism = read("DETERMINISM_RECEIPT.json");
const fullTraceParts = read("FULL_DECISION_TRACE_PARTS.json");

assert.strictEqual(control.machine.V34_full_life_package_commit, "e0fb6a312d8bbc52806603fbc143bf2bcebb3df2");
assert.strictEqual(control.machine.V34_trading_phase_package_commit, "b430bcfff51f89c9466e77b798d4ac5d9fff15ea");
assert.deepStrictEqual(control.window_law.right_precedence, ["exact_start_utc", "known_live_by_utc", "schedule_bound_utc"]);
assert.strictEqual(control.close_law.grading_reads, 0);
assert.strictEqual(start.operative_commit_derived_by_git_path_history, "224417da642a9f378a0d83f76edffe9890cb4a6f");
assert.strictEqual(start.sha256, "1d7fe6a56837ceb0c0b8c932a05daecacc0cefbea94384e16c84975f2ed98ce5");
assert.strictEqual(start.rows, 804);
assert.strictEqual(start.edge_precedence_counts.exact_start_utc, 234);
assert.strictEqual(start.edge_precedence_counts.known_live_by_utc, 507);
assert.strictEqual(start.edge_precedence_counts.schedule_bound_utc, 63);
assert.strictEqual(spans.rows.length, 804);
assert.strictEqual(spans.conservation.pass, true);
assert.strictEqual(edge.post_edge_action_or_fill_or_cap_arm_rows, 0);
assert.strictEqual(edge.post_edge_state_update_rows, 0);
assert.strictEqual(score.STRICT_LAW.aggregate.D, 804);
assert.strictEqual(score.CENSUS_PRICED.aggregate.D, 804);
assert.strictEqual(score.STRICT_LAW.aggregate.close_based_grade, null);
assert.strictEqual(score.CENSUS_PRICED.aggregate.close_based_grade, null);
assert.strictEqual(score.comparison_floor.operator_named_under_par_offer_census_adjusted, 680);
assert.strictEqual(strictFrontier.conservation.pass, true);
assert.strictEqual(censusFrontier.conservation.pass, true);
assert.strictEqual(strictRegret.denominator_legs, 1608);
assert.strictEqual(censusRegret.denominator_legs, 1608);
assert.strictEqual(strictRegret.conservation.pass, true);
assert.strictEqual(censusRegret.conservation.pass, true);
assert.strictEqual(isolation.strict_invariant, true);
assert.strictEqual(isolation.census_invariant, true);
assert.strictEqual(isolation.close_fields_consumed_by_scorecard, 0);
assert.strictEqual(isolation.close_fields_consumed_by_frontier, 0);
assert.strictEqual(isolation.close_fields_consumed_by_regret, 0);
assert.strictEqual(trace.post_edge_rows, 0);
assert.strictEqual(trace.strict_compact_leg_rows, 1608);
assert.strictEqual(trace.census_compact_leg_rows, 1608);
assert.strictEqual(r3.original_R3_joint_reference_only, 68);
assert.strictEqual(r3.conservation.pass, true);
assert.strictEqual(offer.operator_named_under_par_offer_census_adjusted, 680);
assert.strictEqual(offer.historical_tape_completability_binding.strict_sequential_any_price, 680);
assert.strictEqual(forbidden.holdout_accesses, 0);
assert.strictEqual(forbidden.live_accesses, 0);
assert.strictEqual(forbidden.network_runtime_accesses, 0);
assert.strictEqual(forbidden.order_accesses, 0);
assert.strictEqual(forbidden.position_accesses, 0);
assert.strictEqual(rows("STRICT_EVENT_LEDGER.jsonl.gz").length, 804);
assert.strictEqual(rows("CENSUS_PRICED_EVENT_LEDGER.jsonl.gz").length, 804);
assert.strictEqual(determinism.builds, 2);
assert.strictEqual(determinism.byte_identical, true);
assert(fullTraceParts.parts.length >= 2);
assert(fullTraceParts.parts.every((row) => row.bytes <= fullTraceParts.max_part_bytes));
assert.strictEqual(fullTraceParts.parts.reduce((sum, row) => sum + row.bytes, 0), fullTraceParts.source_bytes);
assert(fullTraceParts.parts.every((row) => fs.existsSync(path.join(OUT, row.name))));

console.log("PASS test_window1_v34_w1_causal_measurement");
