#!/usr/bin/env node
"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const repo = path.resolve(__dirname, "../..");
const root = path.join(repo, ".claude/window1_live_v4_replay/v52p_ripeness_gated_role_binding_20260817");
const json = (name) => JSON.parse(fs.readFileSync(path.join(root, name), "utf8"));
let assertions = 0;
const equal = (actual, expected, message) => { assertions += 1; assert.deepStrictEqual(actual, expected, message); };
const check = (value, message) => { assertions += 1; assert(value, message); };

check(fs.existsSync(root));
const control = json("CONTROL_BINDING.json");
equal(control.parent_commit, "fe9387b2832f499b3cf9ed6d64ac576c098d15f0");
equal(control.branch, "codex/window1-v52p-ripeness-gated-role-binding-20260817");
equal(control.score_or_disposition_804_run, false);
const cohort = json("COHORT_SELECTION_RECEIPT.json");
equal(cohort.pins.length, 5);
equal(cohort.fresh_25.length, 25);
equal(cohort.combined_30.length, 30);
for (const key of Object.keys(cohort.exclusions).filter((key) => key.endsWith("fresh25_overlap_count"))) equal(cohort.exclusions[key], 0, key);
const receipt = json("CLAUSE_3_RIPENESS_GATED_ROLE_BINDING_CORRECTION_RECEIPT.json");
equal(receipt.authorized_change, "CLAUSE_3_RIPENESS_GATED_ROLE_BINDING_ONLY");
equal(receipt.parent.commit, "fe9387b2832f499b3cf9ed6d64ac576c098d15f0");
equal(receipt.behavioral_lineage.commit, "6678fd0c13dcc4de2bc153bbf769f5a2a9227ccc");
equal(receipt.ripeness_binding.source.commit, "41c1f7244af3afa4dade63bc9824808090ada41d");
equal(receipt.ripeness_binding.class_gates, { ROLE_DOWN: 0.448, ROLE_STILL: 0.65, ROLE_UP: 0.023 });
equal(receipt.ripeness_binding.category_gates.WTA_CHALL, 0.964);
equal(receipt.frozen_clauses.REFLEX_POST, 0);
const summary = json("RIPENESS_ROLE_BINDING_SUMMARY.json");
equal(summary.terminal_legs, 60);
equal(summary.terminal_rows.length, 60);
equal(summary.source.commit, "41c1f7244af3afa4dade63bc9824808090ada41d");
equal(summary.divergence_rows.length, summary.binding_divergence_receipts);
equal(summary.verified_bound_terminal_legs + (60 - summary.verified_bound_terminal_legs), 60);
const role = json("BENCHMARKED_ROLE_INSTRUMENT_SUMMARY.json");
equal(role.terminal_roles.length, 60);
equal(role.coverage.terminal_legs, 60);
check(role.coverage.called_all_legs_share >= 0 && role.coverage.called_all_legs_share <= 1);
check(role.accuracy.accuracy === null || (role.accuracy.accuracy >= 0 && role.accuracy.accuracy <= 1));
equal(role.rule_binding.ripeness.commit, "41c1f7244af3afa4dade63bc9824808090ada41d");
const flow = json("FLOW_ASSERTIONS.json");
equal(flow.REFLEX_POST_zero.observed, 0);
equal(flow.exact_published_ripeness_source_on_every_evaluation.violations.length, 0);
equal(flow.candidate_role_matches_literal_drift_arithmetic.violations.length, 0);
equal(flow.effective_gate_is_exact_max_and_binding_uses_verified_f.violations.length, 0);
equal(flow.below_gate_abstains_to_V52l.violations.length, 0);
equal(flow.ROLE_UP_STILL_and_below_gate_preserve_V52l_level.violations.length, 0);
equal(flow.every_ROLE_DOWN_consumption_binds_aggregate_and_three_SHAs.violations.length, 0);
equal(flow.scheduled_proxy_is_telemetry_not_decision_basis.violations.length, 0);
equal(flow.pass, true);
const outcomes = json("PER_GAME_OUTCOME_TABLE.json");
equal(outcomes.length, 30);
check(outcomes.every((row) => Object.values(row.leg_macro_recognition).every((leg) => Object.prototype.hasOwnProperty.call(leg, "ripeness"))));
const differential = json("BEFORE_AFTER_DECISION_DIFFERENTIAL_MANIFEST.json");
equal(differential.chunks.reduce((sum, row) => sum + row.rows, 0), differential.rows);
equal(differential.conservation_pass, true);
check(differential.chunks.every((row) => row.bytes < 100000000));
const forbidden = json("FORBIDDEN_ACCESS_RECEIPT.json");
for (const key of ["holdout", "live", "network_runtime", "orders", "positions", "deployment", "full_804_run", "scavenger"]) equal(forbidden[key], false, key);
const deterministic = json("DETERMINISM_RECEIPT.json");
equal(deterministic.clean_builds, 2);
equal(deterministic.byte_identical, true);
equal(deterministic.mismatches.length, 0);

process.stdout.write(`${JSON.stringify({ assertions, failures: 0, omissions: 0, deselections: 0 })}\n`);
