#!/usr/bin/env node
"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");

const repo = path.resolve(__dirname, "../..");
const root = path.join(repo, ".claude/window1_live_v4_replay/v52q_anchor_correction_20260818");
const json = (name) => JSON.parse(fs.readFileSync(path.join(root, name), "utf8"));
let assertions = 0;
const equal = (actual, expected, message) => { assertions += 1; assert.deepStrictEqual(actual, expected, message); };
const check = (value, message) => { assertions += 1; assert(value, message); };

check(fs.existsSync(root));
const control = json("CONTROL_BINDING.json");
equal(control.parent_commit, "020b775cc59ddc4238d33113adf8e6e79e8bb97d");
equal(control.branch, "codex/window1-v52q-anchor-correction-20260818");
equal(control.score_or_disposition_804_run, false);
const cohort = json("COHORT_SELECTION_RECEIPT.json");
equal(cohort.pins.length, 5);
equal(cohort.fresh_25.length, 25);
equal(cohort.combined_30.length, 30);
equal(cohort.excluded_prior_fresh_cohorts.length, 15);
for (const key of Object.keys(cohort.exclusions).filter((key) => key.endsWith("fresh25_overlap_count"))) equal(cohort.exclusions[key], 0, key);
const receipt = json("CLAUSE_3_ROLE_ANCHOR_CORRECTION_CORRECTION_RECEIPT.json");
equal(receipt.authorized_change, "CLAUSE_3_ROLE_ANCHOR_CORRECTION_ONLY");
equal(receipt.parent.commit, "020b775cc59ddc4238d33113adf8e6e79e8bb97d");
equal(receipt.behavioral_lineage.commit, "6678fd0c13dcc4de2bc153bbf769f5a2a9227ccc");
equal(receipt.anchor_binding.method.commit, "e269779b0ec025d55f67d576e3cfb0cb575d5890");
equal(receipt.anchor_binding.method.name, "SPREAD_SETTLE_MID_AT_FORMATION_END");
equal(receipt.anchor_binding.series_floor, "FORMATION_END_INCLUSIVE");
equal(receipt.anchor_binding.discrepancy.commit, "620fe4c1");
equal(receipt.ripeness_binding.source.commit, "41c1f7244af3afa4dade63bc9824808090ada41d");
equal(receipt.frozen_clauses.REFLEX_POST, 0);
const summary = json("BENCHMARKED_ROLE_INSTRUMENT_SUMMARY.json");
equal(summary.terminal_roles.length, 60);
equal(summary.coverage.terminal_legs, 60);
check(summary.runtime_vs_offline_parity.parity >= 0.99);
equal(summary.runtime_vs_offline_parity.claim_at_least_99pct, true);
check(summary.coverage.called_all_legs_share === null || (summary.coverage.called_all_legs_share >= 0 && summary.coverage.called_all_legs_share <= 1));
check(summary.accuracy.accuracy === null || (summary.accuracy.accuracy >= 0 && summary.accuracy.accuracy <= 1));
equal(summary.rule_binding.anchor_correction.series_floor, "FORMATION_END_INCLUSIVE");
const parity = json("ANCHOR_CORRECTION_PARITY_RECEIPT.json");
equal(parity.binding.method.commit, "e269779b0ec025d55f67d576e3cfb0cb575d5890");
equal(parity.runtime_vs_offline_parity.mismatches.length, 0);
const flow = json("FLOW_ASSERTIONS.json");
equal(flow.REFLEX_POST_zero.observed, 0);
equal(flow.exact_benchmark_role_rule_on_every_evaluation.violations.length, 0);
equal(flow.spread_settle_anchor_receipted_on_every_evaluation.violations.length, 0);
equal(flow.anchor_value_matches_bound_ground_truth_leg.violations.length, 0);
equal(flow.causal_price_series_floored_at_formation_end.violations.length, 0);
equal(flow.exact_published_ripeness_source_on_every_evaluation.violations.length, 0);
equal(flow.candidate_role_matches_literal_drift_arithmetic.violations.length, 0);
equal(flow.effective_gate_is_exact_max_and_binding_uses_verified_f.violations.length, 0);
equal(flow.pass, true);
const outcomes = json("PER_GAME_OUTCOME_TABLE.json");
equal(outcomes.length, 30);
check(outcomes.every((row) => Object.values(row.leg_macro_recognition).every((leg) => Object.prototype.hasOwnProperty.call(leg, "anchor_correction"))));
const differential = json("BEFORE_AFTER_DECISION_DIFFERENTIAL_MANIFEST.json");
equal(differential.chunks.reduce((sum, row) => sum + row.rows, 0), differential.rows);
equal(differential.conservation_pass, true);
check(differential.chunks.every((row) => row.bytes < 100000000));
const source = json("SOURCE_HASH_MANIFEST.json");
check(source.files["arb-executor/analysis/window1_v52q_anchor_correction.js"]);
check(source.files["arb-executor/analysis/build_window1_v52q_anchor_correction.js"]);
const forbidden = json("FORBIDDEN_ACCESS_RECEIPT.json");
for (const key of ["holdout", "live", "network_runtime", "orders", "positions", "deployment", "full_804_run", "scavenger"]) equal(forbidden[key], false, key);
const deterministic = json("DETERMINISM_RECEIPT.json");
equal(deterministic.clean_builds, 2);
equal(deterministic.byte_identical, true);
equal(deterministic.mismatches.length, 0);

process.stdout.write(`${JSON.stringify({ assertions, failures: 0, omissions: 0, deselections: 0 })}\n`);
