#!/usr/bin/env node
"use strict";
const assert=require('assert'),fs=require('fs'),path=require('path'),zlib=require('zlib');
const repo=path.resolve(__dirname,'../..'),dir=path.join(repo,'.claude/window1_live_v4_replay/second_leg_x_pricer_v17_20260803');let n=0;const ok=(x,m)=>{assert.ok(x,m);n++;};
const read=n=>JSON.parse(fs.readFileSync(path.join(dir,n))),metrics=read('POPULATION_COMPARISON_V11_V17.json'),control=read('CONTROL_BINDING_V17.json'),time=read('TIME_AND_FLOW_AXIS_DIAGNOSTIC.json'),inversion=read('REALIZED_FALL_INVERSION_RETIREMENT_RECEIPT.json'),changes=read('V11_TO_V17_STREAM_CHANGE_RECEIPT.json');
ok(metrics.v11.events===804&&metrics.v17.events===804,'D=804');ok(metrics.v11.acted_legs===712&&metrics.v17.acted_legs===711,'acted counts');ok(metrics.v17.completed_pairs===184&&metrics.v17.pairs_under_par===92,'pair counts');ok(metrics.v17.both_legs_strictly_below_close===21,'both below');ok(metrics.v17.execution_floor_pair_pass===30,'floor pass');ok(metrics.v17.carried_pairs_strict_one_above_one_below_close===51,'carried pairs');ok(metrics.causal_recovery.both_below_close_delta===0&&metrics.causal_recovery.under_par_delta===-2,'no forced ex-post recovery');
ok(control.x_library.usable_cells===8&&control.x_library.minimum_support.value===20,'eight supported cells');ok(control.timing_consumed===false&&control.realized_fall_inversion_consumed===false,'diagnostics excluded from behavior');ok(changes.changes===5&&changes.rows.every(x=>x.change_receipted_by_x),'five exact X-receipted changes');
const trace=zlib.gunzipSync(fs.readFileSync(path.join(dir,'V11_NON_ACTION_DECISION_TRACE_896.jsonl.gz'))).toString('utf8').trim().split(/\r?\n/).map(JSON.parse);ok(trace.length===896&&new Set(trace.map(x=>x.leg_identity)).size===896,'896 trace');ok(time.fit_population.fit_rows===757&&time.tests_are_separate_not_collapsed===true,'time population');ok(inversion.status==='RETRACTED_AS_GENERAL_RULE'&&inversion.behavior_consumed===false,'inversion retired');
const events=zlib.gunzipSync(fs.readFileSync(path.join(dir,'EVENT_LEDGER.jsonl.gz'))).toString('utf8').trim().split(/\r?\n/).map(JSON.parse);ok(events.length===804&&events.flatMap(e=>Object.values(e.legs)).length===1608,'event and leg conservation');ok(!fs.existsSync(path.join(dir,'RESULTS.json')),'no scorer result');
console.log(`PASS ${n}`);
