#!/usr/bin/env node
"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");
const zlib = require("zlib");
const { macroState, matchesMacroEnvelope, ordinalVerdict, traverseMicroModel } = require("../analysis/window1_interim_elimination_v13.js");

const repo = path.resolve(__dirname, "../.."), fitDir = path.join(repo, ".claude/window1_live_v4_replay/interim_shape_v13_fit_20260803"), out = path.join(repo, ".claude/window1_live_v4_replay/interim_elimination_v13_20260803");
const library = JSON.parse(fs.readFileSync(path.join(fitDir, "INTERIM_SHAPE_LIBRARY_V13.json")));
const coherence = JSON.parse(fs.readFileSync(path.join(out, "SHAPE_COHERENCE_CENSUS.json")));
const calibration = JSON.parse(fs.readFileSync(path.join(out, "MICRO_MICRO_CALIBRATION.json")));
const ordering = JSON.parse(fs.readFileSync(path.join(out, "LEVEL_ORDERING_RECEIPT.json")));
const funnel = JSON.parse(fs.readFileSync(path.join(out, "FUNNEL_AND_FIVE_CEILINGS.json")));
const nonAction = JSON.parse(fs.readFileSync(path.join(out, "NON_ACTION_CENSUS.json")));
const events = zlib.gunzipSync(fs.readFileSync(path.join(out, "POPULATION_EVENT_LEDGER.jsonl.gz"))).toString("utf8").trim().split(/\r?\n/).map(JSON.parse);

assert.strictEqual(macroState({ ask_net: 0, ask_drawdown_from_peak: 0, ask_dip: 0 }), "ANCHOR_OR_UNMOVED");
assert.strictEqual(macroState({ ask_net: -2, ask_dip: -2, ask_drawdown_from_peak: 2 }), "AT_DESCENDING_LOW");
const syntheticShape = { usable_for_signing: true, descent_to_final_reachable_low: { min: 2, max: 3 }, interim_envelopes: [{ macro_states: ["AT_DESCENDING_LOW"], ask_net: [-4, -1], ask_dip: [-4, -1], ask_peak: [0, 2], ask_drawdown_from_peak: [1, 6] }] };
assert(matchesMacroEnvelope(syntheticShape, { prefix: { ask_net: -2, ask_dip: -2, ask_peak: 0, ask_drawdown_from_peak: 2 } }, 0));
assert.strictEqual(ordinalVerdict(syntheticShape, 1).verdict, "LOWER");
assert.strictEqual(ordinalVerdict(syntheticShape, 2).verdict, "UNKNOWN");
assert.strictEqual(ordinalVerdict(syntheticShape, 3).verdict, "FLOOR");
const model = { tree: { type: "SPLIT", feature: "ask_dwell_seconds", threshold: 4, left: { type: "LEAF", leaf_id: "L1", verdict: "NOT_READY", fit_rate: .2, samples: 20, unique_legs: 20 }, right: { type: "LEAF", leaf_id: "L2", verdict: "READY", fit_rate: .8, samples: 20, unique_legs: 20 } } };
assert.strictEqual(traverseMicroModel(model, { ask_dwell_seconds: 3 }).verdict, "NOT_READY");
assert.strictEqual(traverseMicroModel(model, { ask_dwell_seconds: 5 }).verdict, "READY");
assert.strictEqual(traverseMicroModel(model, {}).verdict, "INSUFFICIENT_EVIDENCE");

assert.strictEqual(library.fit_universe.available_formed_book_legs, 1343);
assert.strictEqual(library.census.shapes, 39);
assert.strictEqual(library.census.signable_shapes, 23);
assert.strictEqual(library.census.unusable_shapes, 16);
assert.strictEqual(library.census.signable_members, 1086);
assert.strictEqual(library.census.unusable_members, 257);
assert.strictEqual(library.census.signable_members + library.census.unusable_members, 1343);
const shapes = Object.values(library.groups).flatMap((group) => group.shapes);
assert(shapes.filter((shape) => shape.usable_for_signing).every((shape) => shape.n >= 20 && shape.coherence.ordinal_support_width <= 1));
assert(shapes.every((shape) => !/(FLAT_UNMOVED|UP_CONTINUATION|DOWN_CONTINUATION)/.test(shape.shape_id)));
assert.strictEqual(library.endpoint_labels_runtime_role, "NONE");
assert.strictEqual(Object.keys(library.micro_micro_models).length, 16);
assert.strictEqual(calibration.sample_census.total, 590555);
assert.strictEqual(calibration.sample_census.fit_July_12_17, 363574);
assert.strictEqual(calibration.sample_census.post_fit_July_18_20, 226981);
assert.strictEqual(ordering.levels.length, 5);
assert.strictEqual(ordering.levels[4].level, "MICRO_MICRO_TIMING");
assert.strictEqual(events.length, 804);
assert.strictEqual(events.flatMap((event) => Object.values(event.legs)).length, 1608);
assert.strictEqual(funnel.full_population.acted_legs, 444);
assert.strictEqual(funnel.full_population.completed_pairs, 80);
assert.strictEqual(funnel.full_population.pairs_under_par, 15);
assert.strictEqual(funnel.full_population.both_legs_strictly_below_close, 10);
assert.strictEqual(funnel.full_population.execution_floor_pair_pass, 8);
assert.strictEqual(funnel.strict_late_close_cohort.events, 305);
assert.strictEqual(funnel.strict_late_close_cohort.completed_pairs, 28);
assert.strictEqual(Object.keys(funnel.full_population.ceiling_comparison).length, 5);
assert.strictEqual(nonAction.full_population.no_action, 1164);
assert.strictEqual(nonAction.full_population.V12_unusable_class_non_actions, 971);
assert.strictEqual(nonAction.full_population.V13_non_actions_with_any_unusable_interim_path, 393);
assert.strictEqual(nonAction.full_population.V13_non_actions_with_only_unusable_interim_paths, 214);
assert.strictEqual(funnel.performance_fields.C, null);
assert.strictEqual(funnel.performance_fields.PC, null);
assert.strictEqual(funnel.performance_fields.ranking, null);
const replaySource = fs.readFileSync(path.join(repo, "arb-executor/analysis/build_window1_quote_shape_elimination_replay_v1.js"), "utf8");
assert(replaySource.includes("--interim-elimination-v13"));
assert(replaySource.includes("LOWER_LEVELS_NOT_CONSULTED"));
assert(!replaySource.includes("window1_range_attack_scorer"));
console.log("PASS test_window1_interim_elimination_v13");
