#!/usr/bin/env node
"use strict";

const assert = require("assert");
const fs = require("fs");
const path = require("path");
const zlib = require("zlib");

const repo = path.resolve(__dirname, "../..");
const library = JSON.parse(fs.readFileSync(path.join(repo, ".claude/window1_live_v4_replay/coherent_shape_v12_fit_20260802/COHERENT_QUOTE_SHAPE_LIBRARY_V12.json")));
const out = path.join(repo, ".claude/window1_live_v4_replay/coherent_shape_refit_v12_20260802");
const funnel = JSON.parse(fs.readFileSync(path.join(out, "FUNNEL_AND_FIVE_CEILINGS.json")));
const nonAction = JSON.parse(fs.readFileSync(path.join(out, "NON_ACTION_CENSUS.json")));
const classCensus = JSON.parse(fs.readFileSync(path.join(out, "CLASS_COHERENCE_CENSUS.json")));
const span = JSON.parse(fs.readFileSync(path.join(out, "TAXONOMY_SPAN_RECEIPT.json")));
const events = zlib.gunzipSync(fs.readFileSync(path.join(out, "POPULATION_EVENT_LEDGER.jsonl.gz"))).toString("utf8").trim().split(/\r?\n/).map(JSON.parse);
const shapes = Object.values(library.groups).flatMap((group) => group.shapes), signable = shapes.filter((shape) => shape.usable_for_signing), unusable = shapes.filter((shape) => !shape.usable_for_signing);

assert.strictEqual(library.training_events, 681);
assert.strictEqual(library.training_legs, 1343);
assert.strictEqual(library.excluded_exact_start_events.length, 5);
assert.strictEqual(shapes.length, 68);
assert.strictEqual(signable.length, 21);
assert.strictEqual(unusable.length, 47);
assert(signable.every((shape) => shape.n >= 20));
assert(signable.every((shape) => shape.coherence.ordinal_support_width <= 1));
assert(signable.every((shape) => shape.coherence.status === "PASS"));
assert(unusable.every((shape) => shape.coherence.status === "UNUSABLE"));
assert.strictEqual(signable.reduce((sum, shape) => sum + shape.n, 0), 760);
assert.strictEqual(unusable.reduce((sum, shape) => sum + shape.n, 0), 583);
assert(library.feature_contract.tick_prefix.includes("ask_drawdown_from_peak"));
assert(library.feature_contract.tick_prefix.includes("qualified_ask_descent_count"));
assert.strictEqual(classCensus.fit_universe.requested_development_events_excluding_five, 799);
assert.strictEqual(classCensus.fit_universe.requested_legs_excluding_five, 1598);
assert.strictEqual(classCensus.fit_universe.positively_provable_window_events, 688);
assert.strictEqual(classCensus.fit_universe.positively_provable_window_legs, 1376);
assert.strictEqual(classCensus.fit_universe.excluded_nonpositive_window_legs, 222);
assert.strictEqual(classCensus.fit_universe.positive_window_legs_without_available_formed_book, 33);
assert.strictEqual(classCensus.old_library.classes, 94);
assert.strictEqual(classCensus.old_library.thin_below_20, 72);
assert.strictEqual(span.prior_classes.length, 94);
assert.strictEqual(span.prior_classes_that_cannot_express_observed_descent.length, 14);
assert.strictEqual(events.length, 804);
assert.strictEqual(events.flatMap((event) => event.legs).length, 1608);
assert.strictEqual(funnel.full_population.acted_legs, 257);
assert.strictEqual(funnel.full_population.completed_pairs, 22);
assert.strictEqual(funnel.full_population.pairs_under_par, 5);
assert.strictEqual(funnel.full_population.both_legs_strictly_below_close, 0);
assert.strictEqual(funnel.full_population.execution_floor_pair_pass, 1);
assert.strictEqual(funnel.strict_late_close_cohort.events, 305);
assert.strictEqual(Object.keys(funnel.full_population.ceiling_comparison).length, 5);
assert.strictEqual(nonAction.full_population.no_action, 1351);
assert.strictEqual(nonAction.full_population.primary_causes.UNUSABLE_SHAPE_CLASS_SURVIVED, 971);
assert.strictEqual(nonAction.full_population.primary_causes.SIGNABLE_ADJACENT_ORDINALS_NOT_YET_UNANIMOUS, 160);
assert.strictEqual(funnel.performance_fields.C, null);
assert.strictEqual(funnel.performance_fields.PC, null);
assert.strictEqual(funnel.performance_fields.ranking, null);
const replaySource = fs.readFileSync(path.join(repo, "arb-executor/analysis/build_window1_quote_shape_elimination_replay_v1.js"), "utf8");
assert(replaySource.includes("CLASS_UNUSABLE_THIN"));
assert(replaySource.includes("qualifiedEpisodeRecorded"));
assert(replaySource.includes("--coherent-shape-v12"));
console.log("PASS test_window1_coherent_shape_refit_v12");
