import { useEffect, useState } from 'react';
import { display } from './lab-panels';
type DeskRow=Record<string,unknown>;
type Desk={schema:string;status:string;source_class:string;activation:{read_only_key_verified:boolean;disjoint_cohort_runtime_verified:boolean;worker_os_binding_verified:boolean;cohort_policy_approved:boolean};provenance:Record<string,unknown>;heartbeat:Record<string,unknown>|null;tape_freshness:Record<string,unknown>|null;positions:DeskRow[]|null;resting_bids:DeskRow[]|null;closed_pairs:DeskRow[]|null;missing_sides:DeskRow[]|null;faults:string[]};
export function DeskPanel(){
 const [data,setData]=useState<Desk|null>(null),[error,setError]=useState<string|null>(null),[revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();fetch('/data/desk-status.json',{signal:c.signal,cache:'no-store'}).then(r=>{if(!r.ok||!r.headers.get('content-type')?.includes('application/json'))throw Error('No live paper status source');return r.json()}).then(d=>{if(d.schema!=='LIVE_PAPER_DESK_V1'||d.source_class!=='LIVE_PAPER')throw Error('Unrecognized or non-paper desk source');setData(d);setError(null)}).catch(e=>{if(e.name!=='AbortError'){setData(null);setError(String(e))}});return()=>c.abort()},[revision]);
 const active=data?.status==='LIVE_PAPER'&&data.activation.read_only_key_verified&&data.activation.disjoint_cohort_runtime_verified&&data.activation.worker_os_binding_verified;
 const source=(v:unknown,key:string)=><span title={`LIVE_PAPER / ${key}\n${JSON.stringify(data?.provenance??{})}\nRaw: ${String(v??'STORE SILENT')}`}>{display(v)}</span>;
 function rows(title:string,field:'positions'|'resting_bids'|'closed_pairs'|'missing_sides',cols:string[]){const values=active?data?.[field]:null;return <section><h2>{title}</h2><div className="book-scroll"><table><thead><tr>{cols.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{values?.filter(r=>r.source_class==='LIVE_PAPER').map((r,i)=><tr key={String(r.receipt_id??i)} data-live-game>{cols.map(c=><td key={c} className={c==='cents'||c==='fill_cents'?'terminal-bid':undefined}>{source(r[c],`${field}[${i}].${c}`)}</td>)}</tr>)}</tbody></table></div>{values==null?<p className="terminal-muted">STORE SILENT — no verified live ledger</p>:values.length===0?<p>No recorded entries in this verified snapshot.</p>:null}</section>}
 return <section aria-label="Paper desk"><div className="terminal-toolbar"><h1 className="terminal-fault">PAPER / {active?'VERIFIED SOURCE':'DISCONNECTED'}</h1><button onClick={()=>setRevision(r=>r+1)}>Refresh status</button></div>
 {!active?<p>No live paper ledger is connected.</p>:null}<p className="terminal-muted">No real orders. A later accepted print can establish paper reachability, not queue priority or a certain exchange fill.</p>
 <h2>Activation gates</h2><table><thead><tr><th>Read-only key</th><th>Prospective cohort rule</th><th>Cohort runtime</th><th>Pinned worker</th></tr></thead><tbody><tr><td>{source(data?.activation.read_only_key_verified?'VERIFIED':'UNVERIFIED','activation.read_only_key_verified')}</td><td>{source(data?.activation.cohort_policy_approved?'APPROVED':'UNVERIFIED','activation.cohort_policy_approved')}</td><td>{source(data?.activation.disjoint_cohort_runtime_verified?'VERIFIED':'UNVERIFIED','activation.disjoint_cohort_runtime_verified')}</td><td>{source(data?.activation.worker_os_binding_verified?'VERIFIED':'UNVERIFIED','activation.worker_os_binding_verified')}</td></tr></tbody></table>
 {error?<p role="alert" className="terminal-fault">{error}</p>:null}
 {rows('Positions','positions',['event','side','cents','quantity','fill_receipt','status'])}
 {rows('Resting paper bids','resting_bids',['event','side','cents','Q','X','layer','renewal_status','reason'])}
 {rows('Closed pairs / settlement grades','closed_pairs',['event','grade','pair_sum','captured_cents','offered_cents','settlement_receipt'])}
 {rows('The missing side / explicit evidence','missing_sides',['event','side','disposition','reason','source_receipt'])}
 <h2>Status bar / independent clocks</h2><table><tbody>{[['Recorder heartbeat',data?.heartbeat],['Tape freshness',data?.tape_freshness],['OS sha',data?.provenance.os_sha256],['Ledger sha',data?.provenance.ledger_sha256],['Snapshot time',data?.provenance.captured_at]].map(([k,v])=><tr key={String(k)}><th>{String(k)}</th><td>{source(typeof v==='object'&&v!=null?JSON.stringify(v):v,String(k))}</td></tr>)}</tbody></table>
 <p className="terminal-muted">Historical LAB games are not today's DESK positions. Unsettled games have no final floor/oracle or final grade.</p>
 </section>;
}
