import {useEffect,useState} from 'react';
import {display} from './lab-panels';
type Row=Record<string,any>;
type Scoreboard={schema:string;scope:string;rows:Row[];summaries:Row[];history:Row[];contract:Record<string,string>;inputs:Row[]};
export function ScoreboardPanel({onGame}:{onGame:(event:string)=>void}){
 const [data,setData]=useState<Scoreboard|null>(null),[error,setError]=useState<string|null>(null),[tour,setTour]=useState('ALL');
 useEffect(()=>{const c=new AbortController();fetch('/data/scoreboard.json',{signal:c.signal,cache:'no-cache'}).then(r=>{if(!r.ok)throw Error(`Scoreboard HTTP ${r.status}`);return r.json()}).then(d=>{if(d.schema!=='FACE_SCOREBOARD_V1')throw Error('Unrecognized scoreboard schema');setData(d)}).catch(e=>{if(e.name!=='AbortError')setError(String(e))});return()=>c.abort()},[]);
 if(error)return <p role="alert" className="terminal-fault">STORE SILENT — {error}</p>;
 if(!data)return <p>Loading hash-bound scoreboard…</p>;
 const source=(v:unknown,key:string,record?:Row)=><span title={`${key}\nRaw: ${String(v??'STORE SILENT')}\n${JSON.stringify(record?.source??data.contract)}`}>{display(v)}</span>;
 const rows=data.rows.filter(r=>tour==='ALL'||r.category===tour);
 return <section aria-label="All-game scoreboard"><div className="terminal-toolbar"><h1>SCOREBOARD / LATEST PER GAME</h1><label>Tour <select aria-label="Scoreboard tour" value={tour} onChange={e=>setTour(e.target.value)}>{data.summaries.map(s=><option key={s.category}>{s.category}</option>)}</select></label></div><p className="terminal-muted">{data.scope}. No successful-only selection. Historical revisions are separate below.</p>
 <div className="book-scroll"><table><thead><tr>{['Game','Tour','Grade','Macro','Micro','Trade','Pair','Captured ¢','Offered ¢','Completed'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.event} data-score-game><td><button title={r.event} onClick={()=>onGame(r.event)}>{r.game}</button></td><td>{r.category}</td><td title={r.governing}>{r.letter}</td>{['MACRO','MICRO','TRADE','PAIR'].map(s=>{const section=r.sections.find((x:Row)=>x.name===s);return <td key={s} title={section?.hover_lines.join('\n')}>{section?.line.split(' · ')[0]??'STORE SILENT'}</td>})}<td>{source(r.captured_cents,'grade.OUTCOME.captured_cents',r)}</td><td>{source(r.offered_cents,'grade.OUTCOME.best_capturable_cents',r)}</td><td>{source(r.completed,'grade.OUTCOME.valid_pair_completed',r)}</td></tr>)}</tbody></table></div>
 <h2>Participation and completion / per tour / all indexed games</h2><div className="book-scroll"><table><thead><tr>{['Tour','Games','Considered','Bid','Complete','One-sided','Unfilled','Offer eligible','No offer','Eligible completed','Capture ¢','Offer ¢','Missing outcome'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.summaries.map(s=><tr key={s.category}>{['category','games','considered','bid','complete','one_sided','unfilled','offer_eligible','no_offer','eligible_complete','captured_cents','offered_cents','outcome_missing'].map(k=><td key={k}>{source(s[k],`scoreboard.summaries.${s.category}.${k} · derived by build_scoreboard.mjs`)}</td>)}</tr>)}</tbody></table></div>
 <p className="terminal-muted">Completion uses every indexed game; eligible completion uses games with verified positive offer. Participation starts with this loaded collection, not every listed exchange market. Zero-offer games are retained.</p>
 <h2>Missing sides / stored evidence</h2><table><thead><tr><th>Game</th><th>Side</th><th>Outcome</th><th>Latest action</th><th>Miss cause</th></tr></thead><tbody>{rows.flatMap(r=>r.missing_sides.map((m:Row)=><tr key={r.event+m.side}><td>{r.game}</td><td>{m.side}</td><td>{m.disposition}</td><td title={`${m.receipt}\n${JSON.stringify(m.last_action_tokens)}`}>{m.last_action??'STORE SILENT'}</td><td>{m.reason}</td></tr>))}</tbody></table>
 <h2>Letters over time / immutable run and ruler revisions</h2><p className="terminal-muted">Original grades remain original. A changed rubric is not an OS improvement. History summaries are stored; full historical files remain local where not published.</p><div className="terminal-log"><table><thead><tr><th>Game</th><th>Timestamp</th><th>OS sha</th><th>Trace sha</th><th>Letter</th><th>Capture ratio</th><th>Governed by</th></tr></thead><tbody>{data.history.filter(h=>rows.some(r=>r.event===h.event)).slice().reverse().map((h,i)=><tr key={`${h.url}:${h.revision}:${i}`}><td>{h.event}</td><td>{source(h.timestamp,'grades/index.json timestamp',h)}</td><td title={h.os_sha}>{h.os_sha.slice(0,8)}</td><td title={h.trace_sha}>{h.trace_sha?.slice(0,8)}</td><td>{h.letter??'STORE SILENT'}</td><td>{source(h.capture_ratio,'grades/index.json capture_ratio',h)}</td><td>{h.governing_section}</td></tr>)}</tbody></table></div>
 <details><summary>Metric definitions and input hashes</summary><pre>{JSON.stringify({contract:data.contract,inputs:data.inputs},null,2)}</pre></details>
 </section>;
}
