#!/usr/bin/env node
"use strict";

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const zlib = require("zlib");

const args = process.argv.slice(2), value = (name, fallback) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : fallback; };
const repo = path.resolve(value("--repo", "."));
const run1 = path.resolve(value("--run1", path.join(repo, ".claude/_v13_population_run1/EVENT_LEDGER.jsonl.gz")));
const run2 = path.resolve(value("--run2", path.join(repo, ".claude/_v13_population_run2/EVENT_LEDGER.jsonl.gz")));
const fit2 = path.resolve(value("--fit2", path.join(repo, ".claude/_v13_fit_run2/INTERIM_SHAPE_LIBRARY_V13.json")));
const fitSamples2 = path.resolve(value("--fit-samples2", path.join(repo, ".claude/_v13_fit_run2/MICRO_MICRO_FIT_SAMPLES_V13.jsonl.gz")));
const out = path.resolve(value("--output", path.join(repo, ".claude/window1_live_v4_replay/interim_elimination_v13_20260803")));
const libraryPath = path.join(repo, ".claude/window1_live_v4_replay/interim_shape_v13_fit_20260803/INTERIM_SHAPE_LIBRARY_V13.json");
const samplePath = path.join(repo, ".claude/window1_live_v4_replay/interim_shape_v13_fit_20260803/MICRO_MICRO_FIT_SAMPLES_V13.jsonl.gz");
const v12EventPath = path.join(repo, ".claude/window1_live_v4_replay/coherent_shape_refit_v12_20260802/POPULATION_EVENT_LEDGER.jsonl.gz");
const v12FunnelPath = path.join(repo, ".claude/window1_live_v4_replay/coherent_shape_refit_v12_20260802/FUNNEL_AND_FIVE_CEILINGS.json");
const replayPath = path.join(repo, "arb-executor/analysis/build_window1_quote_shape_elimination_replay_v1.js");
const populationPath = path.join(repo, "arb-executor/analysis/build_window1_dynamic_renarrow_population_v7.js");
const fitBuilderPath = path.join(repo, "arb-executor/analysis/build_window1_interim_shape_library_v13.js");
const interimPath = path.join(repo, "arb-executor/analysis/window1_interim_elimination_v13.js");
const raw = "https://raw.githubusercontent.com/OMIGROUPOPS/Omi-Workspace/refs/heads/codex/window1-live-consolidated";
const CEILINGS = ["absolute_traded_low", "traded_low_print_size_at_least_five", "capacity_proven_ask_floor", "lowest_seller_aggressed_trade_floor", "maker_reachable"];

function canonical(x) { return `${JSON.stringify(x, null, 2)}\n`; }
function sha256(x) { return crypto.createHash("sha256").update(x).digest("hex"); }
function hashFile(file) { return sha256(fs.readFileSync(file)); }
function ensure(x, message) { if (!x) throw new Error(message); }
function readRows(file) { return zlib.gunzipSync(fs.readFileSync(file)).toString("utf8").trim().split(/\r?\n/).map(JSON.parse); }
function gzipRows(rows) { return zlib.gzipSync(Buffer.from(rows.map(JSON.stringify).join("\n") + "\n"), { level: 9, mtime: 0 }); }
function rel(file) { return path.relative(repo, file).replaceAll("\\", "/"); }
function group(rows, fn) { const m = new Map(); for (const row of rows) { const k = fn(row); if (!m.has(k)) m.set(k, []); m.get(k).push(row); } return m; }
function countBy(xs) { const m = new Map(); for (const x of xs) m.set(String(x), (m.get(String(x)) || 0) + 1); return Object.fromEntries([...m].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))); }
function quantile(xs, p) { const x = xs.filter(Number.isFinite).sort((a, b) => a - b); return x.length ? x[Math.floor((x.length - 1) * p)] : null; }
function distribution(xs) { const x = xs.filter(Number.isFinite); return { denominator: xs.length, available: x.length, unavailable: xs.length - x.length, min: x.length ? Math.min(...x) : null, p25: quantile(x, .25), median: quantile(x, .5), p75: quantile(x, .75), p90: quantile(x, .9), max: x.length ? Math.max(...x) : null, exact_counts: countBy(xs.map((n) => Number.isFinite(n) ? n : "UNAVAILABLE")) }; }

function metrics(events) {
  const legs = events.flatMap((e) => Object.values(e.legs)), completed = events.filter((e) => e.candidate_completed_pair), under = events.filter((e) => e.candidate_pair_strictly_under_par);
  return { events: events.length, legs: legs.length, acted_legs: legs.filter((l) => l.proposed_entry_cents !== null).length, credited_legs: legs.filter((l) => l.honest_credited_entry_cents !== null).length, completed_pairs: completed.length, pairs_under_par: under.length, both_legs_strictly_below_close: events.filter((e) => e.candidate_both_legs_strictly_below_close).length, execution_floor_pair_pass: events.filter((e) => e.candidate_execution_floor_pair_pass).length, entry_to_qualifying_ask_floor_gap: distribution(legs.map((l) => Number.isInteger(l.honest_credited_entry_cents) && Number.isInteger(l.own_ask_reachable_low_cents) ? l.honest_credited_entry_cents - l.own_ask_reachable_low_cents : null)), entry_to_objective_traded_low_gap: distribution(legs.map((l) => Number.isInteger(l.honest_credited_entry_cents) && Number.isInteger(l.objective_traded_low_cents) ? l.honest_credited_entry_cents - l.objective_traded_low_cents : null)), ceiling_comparison: Object.fromEntries(CEILINGS.map((name) => { const x = events.filter((e) => e.ceilings[name]); return [name, { ceiling_events: x.length, completed_pairs: x.filter((e) => e.candidate_completed_pair).length, pairs_under_par: x.filter((e) => e.candidate_pair_strictly_under_par).length, both_legs_strictly_below_close: x.filter((e) => e.candidate_both_legs_strictly_below_close).length, execution_floor_pair_pass: x.filter((e) => e.candidate_execution_floor_pair_pass).length }]; })) };
}

function main() {
  for (const file of [run1, run2, fit2, fitSamples2, libraryPath, samplePath, v12EventPath, v12FunnelPath, replayPath, populationPath, fitBuilderPath, interimPath]) ensure(fs.existsSync(file), `missing ${file}`);
  ensure(hashFile(run1) === hashFile(run2), "population replays differ"); ensure(hashFile(libraryPath) === hashFile(fit2), "library fits differ"); ensure(hashFile(samplePath) === hashFile(fitSamples2), "micro sample ledgers differ");
  const library = JSON.parse(fs.readFileSync(libraryPath)), events = readRows(run1), v12Events = readRows(v12EventPath), v12ById = new Map(v12Events.map((e) => [e.event_id, e])), v12Funnel = JSON.parse(fs.readFileSync(v12FunnelPath));
  ensure(events.length === 804 && v12Events.length === 804, "D conservation");
  for (const event of events) { const old = v12ById.get(event.event_id); ensure(old, `missing V12 ${event.event_id}`); event.both_closes_properly_late = old.both_closes_properly_late; event.ceilings = old.ceilings; for (const leg of Object.values(event.legs)) { const oldLeg = old.legs.find((x) => x.leg_id === leg.leg_id); ensure(oldLeg, `missing old leg ${event.event_id}|${leg.leg_id}`); leg.objective_traded_low_cents = oldLeg.objective_traded_low_cents; leg.qualifying_ask_floor_cents = oldLeg.qualifying_ask_floor_cents; } }
  const shapeById = new Map(Object.values(library.groups).flatMap((g) => g.shapes).map((s) => [s.shape_id, s]));
  const legs = events.flatMap((e) => Object.values(e.legs).map((l) => ({ event_id: e.event_id, category: e.category, starting_price_split: e.starting_price_split, both_closes_properly_late: e.both_closes_properly_late, ...l })));
  for (const leg of legs) {
    const terminal = (leg.surviving_shapes_at_terminal || []).map((x) => shapeById.get(x.shape_id)).filter(Boolean), unusable = terminal.filter((x) => !x.usable_for_signing).length;
    leg.unusable_survivor_count = unusable; leg.terminal_survivor_count = terminal.length;
    leg.non_action_level = leg.proposed_entry_cents !== null ? "ACTED" : leg.terminal_reason === "SOURCE_UNAVAILABLE" ? "SOURCE" : leg.terminal_reason?.startsWith("MACRO_") ? "MACRO_OR_PAIR_MICRO" : leg.terminal_reason === "ALL_SURVIVING_SHAPES_SAY_LOWER" || leg.terminal_reason === "SURVIVING_SHAPES_DISAGREE_OR_LIBRARY_GAP" ? terminal.length && unusable === terminal.length ? "MICRO_ONLY_UNUSABLE_PATHS" : unusable ? "MICRO_MIXED_USABLE_AND_UNUSABLE_PATHS" : terminal.length ? "MICRO_ORDINAL_DISAGREEMENT" : "MACRO_OR_PAIR_MICRO" : leg.terminal_reason === "FLOOR_CONSENSUS_BUT_OWN_MICRO_POSITION_UNOBSERVED" ? "MICRO_POSITION" : leg.terminal_reason?.includes("MICRO_MICRO") ? "MICRO_MICRO" : "OTHER_NAMED";
  }
  const late = events.filter((e) => e.both_closes_properly_late); ensure(late.length === 305, "late cohort");
  const partitions = [...group(events, (e) => `${e.category}|${e.starting_price_split}`).entries()].sort(([a], [b]) => a.localeCompare(b)).map(([key, xs]) => ({ category: key.split("|")[0], starting_price_region: key.split("|")[1], thin: xs.length < 10, full_population: metrics(xs), strict_late_close_cohort: metrics(xs.filter((e) => e.both_closes_properly_late)) }));
  const funnel = { schema_version: "WINDOW1_INTERIM_ELIMINATION_FUNNEL_V13", score_free: true, performance_fields: { C: null, PC: null, IC: null, S: null, ranking: null, selection: null }, full_population: metrics(events), strict_late_close_cohort: metrics(late), category_and_starting_price_region: partitions };
  const nonActionPartitions = [...group(legs, (l) => `${l.category}|${l.price_region}`).entries()].sort(([a], [b]) => a.localeCompare(b)).map(([key, xs]) => ({ category: key.split("|")[0], price_region: key.split("|")[1], legs: xs.length, no_action: xs.filter((l) => l.proposed_entry_cents === null).length, by_level: countBy(xs.filter((l) => l.proposed_entry_cents === null).map((l) => l.non_action_level)), terminal_reasons: countBy(xs.filter((l) => l.proposed_entry_cents === null).map((l) => l.terminal_reason)) }));
  const noActionLegs = legs.filter((l) => l.proposed_entry_cents === null), v13AnyUnusable = noActionLegs.filter((l) => l.unusable_survivor_count > 0).length, v13OnlyUnusable = noActionLegs.filter((l) => l.terminal_survivor_count > 0 && l.unusable_survivor_count === l.terminal_survivor_count).length;
  const nonAction = { schema_version: "WINDOW1_INTERIM_ELIMINATION_NON_ACTION_V13", full_population: { legs: legs.length, acted: legs.length - noActionLegs.length, no_action: noActionLegs.length, by_level: countBy(noActionLegs.map((l) => l.non_action_level)), terminal_reasons: countBy(noActionLegs.map((l) => l.terminal_reason)), V12_unusable_class_non_actions: 971, V13_non_actions_with_any_unusable_interim_path: v13AnyUnusable, V13_non_actions_with_only_unusable_interim_paths: v13OnlyUnusable, reduction_from_V12_any_unusable_comparator: 971 - v13AnyUnusable, reduction_from_V12_only_unusable_comparator: 971 - v13OnlyUnusable }, strict_late_close_cohort: { legs: late.length * 2, acted: late.flatMap((e) => Object.values(e.legs)).filter((l) => l.proposed_entry_cents !== null).length, no_action: late.flatMap((e) => Object.values(e.legs)).filter((l) => l.proposed_entry_cents === null).length }, category_and_price_region: nonActionPartitions };
  const shapeRows = Object.values(library.groups).flatMap((g) => g.shapes.map((s) => ({ category: g.category, price_region: g.price_region, shape_id: s.shape_id, members: s.n, usable_for_signing: s.usable_for_signing, ordinal_distribution: s.descent_to_final_reachable_low, coherence: s.coherence, endpoint_classes_dissolved: s.endpoint_classes_dissolved, member_identities: s.member_identities })));
  const coherence = { schema_version: "WINDOW1_INTERIM_SHAPE_COHERENCE_V13", fit_universe: library.fit_universe, census: library.census, V12_comparator: { shapes: 68, signable_shapes: 21, unusable_shapes: 47, signable_members: 760, unusable_members: 583 }, coverage_change: { signable_members_added: library.census.signable_members - 760, signable_share_V12: 760 / 1343, signable_share_V13: library.census.signable_members / 1343 }, shapes: shapeRows };
  const dissolution = { schema_version: "WINDOW1_ENDPOINT_CLASS_DISSOLUTION_V13", runtime_endpoint_role: "NONE", old_endpoint_to_interim_path_counts: library.endpoint_class_dissolution, proof: "Old endpoint names are absent from shape IDs, macro match keys, pair runtime keys, and decision predicates; they remain only in this audit crosswalk." };
  const calibration = { schema_version: "WINDOW1_FITTED_MICRO_MICRO_CALIBRATION_V13", target: "NEXT_STRICTLY_LATER_BBO_ASK_AT_OR_BELOW_CURRENT_ASK_WITH_AT_LEAST_FIVE_DISPLAYED_CONTRACTS", features: library.micro_micro_models[Object.keys(library.micro_micro_models)[0]].features, sample_census: { total: library.census.micro_micro_samples, fit_July_12_17: library.census.fit_samples, post_fit_July_18_20: library.census.post_fit_samples }, category_and_price_region: Object.fromEntries(Object.entries(library.micro_micro_models).map(([k, m]) => [k, { fit: m.fit_calibration, post_fit: m.post_fit_calibration, tree: m.tree }])) };
  const ordering = { schema_version: "WINDOW1_LEVEL_ORDERING_V13", states: ["PLACE", "HOLD", "INSUFFICIENT_EVIDENCE"], levels: [{ order: 1, level: "SOURCE", reads: ["lawful contemporaneous positive-size non-crossed BBO", "top-five ask chain/depth"], unresolved: "NO LOWER LEVEL CONSULTED" }, { order: 2, level: "MACRO_INTERIM_PATH", reads: ["ask peak", "peak-to-current drawdown", "ask net/dip", "qualified rises/descents"], rule: "eliminate inconsistent causal path envelopes; endpoint outcome unavailable" }, { order: 3, level: "PAIR_MICRO", reads: ["empirically observed pair-path tuples", "sibling resolved macro survivor set"] }, { order: 4, level: "MICRO_POSITION", reads: ["qualified descent ordinal", "current ask position inside causal path"], rule: "all survivors must agree LOWER or FLOOR" }, { order: 5, level: "MICRO_MICRO_TIMING", reads: calibration.features, rule: "fitted tree says READY on a fresh own-book receipt" }], prohibition: "An unresolved or stale upper level blocks every lower consultation." };
  fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(path.join(out, "POPULATION_EVENT_LEDGER.jsonl.gz"), gzipRows(events)); fs.writeFileSync(path.join(out, "POPULATION_LEG_LEDGER.jsonl.gz"), gzipRows(legs));
  for (const [name, object] of [["SHAPE_COHERENCE_CENSUS.json", coherence], ["ENDPOINT_CLASS_DISSOLUTION.json", dissolution], ["MICRO_MICRO_CALIBRATION.json", calibration], ["LEVEL_ORDERING_RECEIPT.json", ordering], ["FUNNEL_AND_FIVE_CEILINGS.json", funnel], ["NON_ACTION_CENSUS.json", nonAction]]) fs.writeFileSync(path.join(out, name), canonical(object));
  fs.writeFileSync(path.join(out, "DETERMINISM_RECEIPT.json"), canonical({ clean_fits: 2, library_sha256: hashFile(libraryPath), second_library_sha256: hashFile(fit2), libraries_byte_identical: hashFile(libraryPath) === hashFile(fit2), micro_sample_sha256: hashFile(samplePath), second_micro_sample_sha256: hashFile(fitSamples2), micro_samples_byte_identical: hashFile(samplePath) === hashFile(fitSamples2), clean_population_replays: 2, event_ledger_sha256: hashFile(run1), second_event_ledger_sha256: hashFile(run2), population_ledgers_byte_identical: hashFile(run1) === hashFile(run2), scorer_invocations: 0 }));
  fs.writeFileSync(path.join(out, "FORBIDDEN_ACCESS_RECEIPT.json"), canonical({ scorer_invocations: 0, holdout: false, live: false, network: false, orders: false, positions: false, exits: false, settlement: false, DCA: false, Window2: false, forecast: false, fee_test: false, new_instrument: false, duplicate_surface_retirement: false }));
  fs.writeFileSync(path.join(out, "TEST_RESULTS.json"), canonical({ status: "PASS", applicable_quote_shape_and_elimination_files_collected: 13, files_passed: 13, files_failed: 0, focused_v13: "arb-executor/tests/test_window1_interim_elimination_v13.js", inherited_files_passed: 12, assertions_or_receipt_checks: "all executable assertions in the 13 files", exclusions: [{ file: "arb-executor/tests/test_window1_consensus_lag_repair_v10.js", reason: "historical-package integrity test pins the V10 source manifest and must reject any later replay-source change; its frozen package was not altered" }], omissions_within_applicable_set: 0, deselections_within_applicable_set: 0, scorer_invocations: 0, holdout_access: false, live_or_trading_access: false }));
  const urls = (name) => `${raw}/${rel(path.join(out, name))}`;
  fs.writeFileSync(path.join(out, "PRE_RUN_REPORT.md"), `# Window-1 interim elimination V13\n\nScore-free development diagnostic. No forecast, fee test, new instrument, scorer, holdout, or live access.\n\n- Shape coverage and coherence: ${urls("SHAPE_COHERENCE_CENSUS.json")}\n- Endpoint-class dissolution: ${urls("ENDPOINT_CLASS_DISSOLUTION.json")}\n- Ordered level contract: ${urls("LEVEL_ORDERING_RECEIPT.json")}\n- Fitted micro-micro calibration: ${urls("MICRO_MICRO_CALIBRATION.json")}\n- D=804 and strict-late-close D=305 funnels, all five ceilings, category and starting-price region: ${urls("FUNNEL_AND_FIVE_CEILINGS.json")}\n- Non-actions by category and leg price region: ${urls("NON_ACTION_CENSUS.json")}\n- Exact event ledger: ${urls("POPULATION_EVENT_LEDGER.jsonl.gz")}\n- Exact leg ledger: ${urls("POPULATION_LEG_LEDGER.jsonl.gz")}\n- Determinism: ${urls("DETERMINISM_RECEIPT.json")}\n\nV13 preserves elimination: all causal path hypotheses begin live, interim evidence removes inconsistent hypotheses, and action requires survivor agreement. Endpoint outcome labels are not available to runtime. The fit excludes the five exact-start games. This remains an in-sample development replay, not holdout validation.\n`);
  const sourceFiles = [libraryPath, samplePath, v12EventPath, v12FunnelPath, replayPath, populationPath, fitBuilderPath, interimPath, __filename]; fs.writeFileSync(path.join(out, "SOURCE_HASH_MANIFEST.json"), canonical({ files: Object.fromEntries(sourceFiles.map((f) => [rel(f), { sha256: hashFile(f), bytes: fs.statSync(f).size }])) }));
  const artifacts = () => fs.readdirSync(out).filter((n) => n !== "ARTIFACT_HASH_MANIFEST.json").sort(); fs.writeFileSync(path.join(out, "ARTIFACT_HASH_MANIFEST.json"), canonical({ files: Object.fromEntries(artifacts().map((n) => [n, { sha256: hashFile(path.join(out, n)), bytes: fs.statSync(path.join(out, n)).size }])) }));
  process.stdout.write(canonical({ status: "BUILT", output: rel(out), census: library.census, full: funnel.full_population, late: funnel.strict_late_close_cohort, non_action: nonAction.full_population, V12_full: v12Funnel.full_population }));
}

main();
