#!/usr/bin/env node
"use strict";

const crypto=require('crypto'),fs=require('fs'),path=require('path'),zlib=require('zlib');
const args=process.argv.slice(2),value=(n,f)=>{const i=args.indexOf(n);return i>=0?args[i+1]:f;};
const repo=path.resolve(value('--repo','.'));
const out=path.resolve(value('--output',path.join(repo,'.claude/window1_live_v4_replay/second_leg_x_pricer_v17_20260803')));
const candidatePath=path.resolve(value('--candidate',path.join(out,'EVENT_LEDGER.jsonl.gz')));
const v11EventPath=path.join(repo,'.claude/window1_live_v4_replay/persistence_floor_repair_v11_20260802/POPULATION_EVENT_LEDGER.jsonl.gz');
const v11LegPath=path.join(repo,'.claude/window1_live_v4_replay/persistence_floor_repair_v11_20260802/POPULATION_LEG_LEDGER.jsonl.gz');
const xLibraryPath=path.join(repo,'.claude/window1_live_v4_replay/second_leg_x_pricer_fit_v17_20260803/SECOND_LEG_X_CONDITIONAL_LIBRARY.json');
const timePath=path.join(out,'TIME_AND_FLOW_AXIS_DIAGNOSTIC.json');
const inversionPath=path.join(repo,'.claude/window1_live_v4_replay/pair_coupling_diagnostic_v16_20260803/PAIR_INVERSION_LAW_RECEIPT.json');
const v16ConclusionPath=path.join(repo,'.claude/window1_live_v4_replay/pair_coupling_diagnostic_v16_20260803/DIAGNOSTIC_CONCLUSION.json');
const deterministicPopulationPath=path.resolve(value('--deterministic-population',path.join(repo,'.claude/_tmp_v17_determinism_run')));
const deterministicTimePath=path.resolve(value('--deterministic-time',path.join(repo,'.claude/_tmp_v17_time_determinism')));
const raw='https://raw.githubusercontent.com/OMIGROUPOPS/Omi-Workspace/refs/heads/codex/window1-live-consolidated';
function canonical(x){return `${JSON.stringify(x,null,2)}\n`;}
function sha(bytes){return crypto.createHash('sha256').update(bytes).digest('hex');}
function rows(file){return zlib.gunzipSync(fs.readFileSync(file)).toString('utf8').trim().split(/\r?\n/).map(JSON.parse);}
function gz(rows){return zlib.gzipSync(Buffer.from(rows.map(JSON.stringify).join('\n')+'\n'),{level:9,mtime:0});}
function rel(file){return path.relative(repo,file).replace(/\\/g,'/');}
function ensure(x,m){if(!x)throw new Error(m);}
function eventMetrics(events){const legs=events.flatMap(e=>Array.isArray(e.legs)?e.legs:Object.values(e.legs)),completed=events.filter(e=>e.completed_pair??e.candidate_completed_pair),under=events.filter(e=>e.pair_under_par??e.candidate_pair_strictly_under_par);return {events:events.length,legs:legs.length,acted_legs:legs.filter(l=>l.acted??l.proposed_entry_cents!==null).length,credited_legs:legs.filter(l=>l.credited??l.honest_credited_entry_cents!==null).length,completed_pairs:completed.length,pairs_under_par:under.length,both_legs_strictly_below_close:events.filter(e=>e.both_legs_strictly_below_close??e.candidate_both_legs_strictly_below_close).length,execution_floor_pair_pass:events.filter(e=>e.candidate_execution_floor_pair_pass??((e.pair_under_par)&&e.legs.every(l=>Number.isFinite(l.entry_minus_qualifying_ask_floor_cents)&&l.entry_minus_qualifying_ask_floor_cents<=0))).length,carried_pairs_strict_one_above_one_below_close:events.filter(e=>{const ls=Array.isArray(e.legs)?e.legs:Object.values(e.legs),d=ls.map(l=>l.entry_minus_own_window1_close_cents??l.delta_to_own_window1_close_cents);return (e.completed_pair??e.candidate_completed_pair)&&d.some(x=>x>0)&&d.some(x=>x<0);}).length};}
function summarizeTime(receipt){const tests=['leg_two_own_t_minus_scheduled','leg_two_own_t_minus_actual_bell','leg_one_floor_t_minus_scheduled','leg_one_floor_t_minus_actual_bell','climber_first_ordering','joint_flow_state'];const summarize=(cells,name)=>{const ms=cells.map(c=>c.tests[name]).filter(Boolean);return {cells:ms.length,usable_cells:ms.filter(x=>x.usable).length,tighter_cells:ms.filter(x=>x.usable&&x.conclusion==='TIGHTER').length,not_tighter_cells:ms.filter(x=>x.usable&&x.conclusion!=='TIGHTER').length,reductions:ms.filter(x=>x.usable).map((x,i)=>({partition:cells[i]?.partition,n:x.n,p90_p10_uncertainty_reduction_cents:x.p90_p10_uncertainty_reduction_cents,conclusion:x.conclusion}))};};return {by_category_and_starting_price_split:Object.fromEntries(tests.map(t=>[t,summarize(receipt.by_category_and_starting_price_split,t)])),by_category_and_first_leg_price_region:Object.fromEntries(tests.map(t=>[t,summarize(receipt.by_category_and_first_leg_price_region,t)])),prints_per_interval:Object.fromEntries([60,300,900,1800].map(w=>[`${w}s`,{by_category_and_starting_price_split:summarize(receipt.by_category_and_starting_price_split.map(c=>({...c,tests:{x:c.tests.prints_per_interval[`${w}s`]}})),'x'),by_category_and_first_leg_price_region:summarize(receipt.by_category_and_first_leg_price_region.map(c=>({...c,tests:{x:c.tests.prints_per_interval[`${w}s`]}})),'x')}])),spread_tightening:Object.fromEntries([300,900,1800].map(w=>[`${w}s`,{by_category_and_starting_price_split:summarize(receipt.by_category_and_starting_price_split.map(c=>({...c,tests:{x:c.tests.spread_tightening[`${w}s`]}})),'x'),by_category_and_first_leg_price_region:summarize(receipt.by_category_and_first_leg_price_region.map(c=>({...c,tests:{x:c.tests.spread_tightening[`${w}s`]}})),'x')}]))};}

function main(){
  const v11Events=rows(v11EventPath),v11Legs=rows(v11LegPath),candidate=rows(candidatePath),xlib=JSON.parse(fs.readFileSync(xLibraryPath)),time=JSON.parse(fs.readFileSync(timePath)),v16=JSON.parse(fs.readFileSync(v16ConclusionPath));
  ensure(v11Events.length===804&&v11Legs.length===1608&&candidate.length===804,'population mismatch');
  const v11ByLeg=new Map(v11Legs.map(l=>[l.leg_identity,l])),candidateByLeg=new Map(candidate.flatMap(e=>Object.values(e.legs).map(l=>[`${e.event_id}|${l.leg_id}`,{event:e,leg:l}])));
  const changes=[];for(const [id,b] of v11ByLeg){const n=candidateByLeg.get(id);ensure(n,`missing ${id}`);const after=n.leg.honest_credited_entry_cents;if(Boolean(b.acted)!==Boolean(n.leg.proposed_entry_cents!==null)||b.entry_cents!==after)changes.push({leg_identity:id,event_id:b.event_id,category:b.category,price_region:b.price_region,starting_price_split:b.starting_price_split,v11:{acted:b.acted,entry_cents:b.entry_cents,action_timestamp_epoch:b.action_timestamp_epoch,terminal_reason:b.terminal_reason},v17:{acted:n.leg.proposed_entry_cents!==null,entry_cents:after,action_timestamp_epoch:n.leg.action_timestamp_epoch,terminal_reason:n.leg.terminal_reason},x_decisions:n.leg.second_leg_x_pricer_decisions,change_receipted_by_x:n.leg.second_leg_x_pricer_decisions.length>0});}
  ensure(changes.every(x=>x.change_receipted_by_x),'unreceipted stream change');
  const baselineNonActions=v11Legs.filter(l=>!l.acted);ensure(baselineNonActions.length===896,'expected 896 V11 nonactions');
  const trace=baselineNonActions.sort((a,b)=>a.leg_identity.localeCompare(b.leg_identity)).map(b=>{const n=candidateByLeg.get(b.leg_identity).leg;return {leg_identity:b.leg_identity,event_id:b.event_id,category:b.category,price_region:b.price_region,starting_price_split:b.starting_price_split,ticker:b.ticker,baseline_v11:{acted:false,terminal_reason:b.terminal_reason,qualifying_ask_floor_cents:b.qualifying_ask_floor_cents,objective_traded_low_cents:b.objective_traded_low_cents,own_window1_close_cents:b.own_window1_close_cents,decision_receipt:b.lag_diagnostic_v10},v17_decision_process:[{level:'FIRST_LEG_X_CONDITIONAL_SHAPE_ELIMINATION',state_changes:n.second_leg_x_pricer_decisions||[]},{level:'FROZEN_V11_LOWER_LEVELS',terminal_reason:n.terminal_reason,placement:n.placement}],v17_outcome:{acted:n.proposed_entry_cents!==null,credited:n.honest_credited_entry_cents!==null,entry_cents:n.honest_credited_entry_cents,action_timestamp_epoch:n.action_timestamp_epoch,t_minus_scheduled_seconds:n.t_minus_scheduled_seconds,t_minus_actual_bell_seconds:n.t_minus_actual_bell_seconds,qualifying_ask_floor_cents:n.own_ask_reachable_low_cents,delta_to_qualifying_ask_floor_cents:n.delta_to_own_ask_reachable_low_cents,own_window1_close_cents:n.own_window1_close_cents,delta_to_close_cents:n.delta_to_own_window1_close_cents}};});
  fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'V11_TO_V17_STREAM_CHANGE_RECEIPT.json'),canonical({schema_version:'WINDOW1_V11_TO_V17_SECOND_LEG_X_STREAM_CHANGE',changes:changes.length,rows:changes}));fs.writeFileSync(path.join(out,'V11_NON_ACTION_DECISION_TRACE_896.jsonl.gz'),gz(trace));
  const inversion={schema_version:'WINDOW1_REALIZED_FALL_INVERSION_RETIREMENT_V17',source_sha256:sha(fs.readFileSync(inversionPath)),v16_finding:v16.inversion_move_and_speed,status:'RETRACTED_AS_GENERAL_RULE',behavior_consumed:false,retained_scope:'CELL_SPECIFIC_DESCRIPTIVE_OBSERVATION_ONLY',rationale:'Only 2/8 supported ask-floor cells and 3/8 supported traded-floor cells tightened; it is not general.'};fs.writeFileSync(path.join(out,'REALIZED_FALL_INVERSION_RETIREMENT_RECEIPT.json'),canonical(inversion));
  const timeConclusion={schema_version:'WINDOW1_TIME_AXIS_RETEST_CONCLUSION_V17',behavior_consumed:false,tests_are_not_collapsed:true,source_sha256:sha(fs.readFileSync(timePath)),summary:summarizeTime(time),fence:'Leg-two own floor T-minus is ex-post descriptive. No time or flow field enters V17 policy.'};fs.writeFileSync(path.join(out,'TIME_AXIS_RETEST_CONCLUSION.json'),canonical(timeConclusion));
  const metrics={schema_version:'WINDOW1_SECOND_LEG_X_POPULATION_COMPARISON_V17',score_free:true,v11:eventMetrics(v11Events),v17:eventMetrics(candidate),ex_post_v16_prize:{both_below_close_from:21,both_below_close_to:31,under_par_from:94,under_par_to:112},causal_recovery:{both_below_close_delta:eventMetrics(candidate).both_legs_strictly_below_close-21,under_par_delta:eventMetrics(candidate).pairs_under_par-94},ruling:'CAUSAL_X_DISTRIBUTION_DID_NOT_RECOVER_THE_EX_POST_PRIZE; DO_NOT_TUNE_POST_HOC'};fs.writeFileSync(path.join(out,'POPULATION_COMPARISON_V11_V17.json'),canonical(metrics));
  const control={schema_version:'WINDOW1_SECOND_LEG_X_CONTROL_BINDING_V17',score_free:true,frozen_v11:{event_sha256:sha(fs.readFileSync(v11EventPath)),leg_sha256:sha(fs.readFileSync(v11LegPath))},x_library:{sha256:sha(fs.readFileSync(xLibraryPath)),cells:Object.keys(xlib.cells).length,usable_cells:Object.values(xlib.cells).filter(c=>c.usable).length,fit_rows:xlib.population.fit_rows,excluded_exact_start_events:xlib.population.excluded_exact_start_events,minimum_support:xlib.minimum_support},policy_law:'After a strictly earlier first-leg action/fill X, eliminate sibling shape hypotheses only when leave-one-event-out P10-P90 shape-floor support is disjoint from the leave-one-event-out X-conditional sibling-floor distribution. Thin cells and thin shape support abstain.',constants_changed:0,timing_consumed:false,realized_fall_inversion_consumed:false};fs.writeFileSync(path.join(out,'CONTROL_BINDING_V17.json'),canonical(control));
  const identity={schema_version:'WINDOW1_FROZEN_V11_SOURCE_IDENTITY_V17',frozen_v11_source_commit:'823a739daed7af6073e48ec037cff05db8f3d494',frozen_v11_replay_blob:'9cdd95ccc33202f6b095cd430e27fd5d27fd637b',frozen_v11_population_builder_blob:'f1cd60dbe9f0e773baf425e49d77269e70669559',v17_replay_sha256:sha(fs.readFileSync(path.join(repo,'arb-executor/analysis/build_window1_quote_shape_elimination_replay_v11_frozen.js'))),law:'V17 starts from the exact V11 Git blobs; only the X distributional narrowing and receipt fields are added.'};fs.writeFileSync(path.join(out,'FROZEN_V11_SOURCE_IDENTITY_RECEIPT.json'),canonical(identity));
  const priorDetPath=path.join(out,'DETERMINISM_RECEIPT_V17.json'),priorDet=fs.existsSync(priorDetPath)?JSON.parse(fs.readFileSync(priorDetPath)):null;
  const detFiles=[['population_event_ledger','EVENT_LEDGER.jsonl.gz',deterministicPopulationPath],['population_summary','POPULATION_SUMMARY.json',deterministicPopulationPath],['population_conservation','CONSERVATION_RECEIPT.json',deterministicPopulationPath],['time_axis_diagnostic','TIME_AND_FLOW_AXIS_DIAGNOSTIC.json',deterministicTimePath],['time_axis_row_ledger','TIME_AND_FLOW_ROW_LEDGER.jsonl.gz',deterministicTimePath]].map(([name,file,other])=>{const a=path.join(out,file),b=path.join(other,file),ah=sha(fs.readFileSync(a)),prior=priorDet?.files?.find(x=>x.name===name),bh=fs.existsSync(b)?sha(fs.readFileSync(b)):prior?.run2_sha256;ensure(ah===bh,`determinism mismatch ${file}`);return {name,file,run1_sha256:ah,run2_sha256:bh,byte_identical:true};});fs.writeFileSync(priorDetPath,canonical({schema_version:'WINDOW1_SECOND_LEG_X_DETERMINISM_V17',clean_population_builds:2,clean_time_flow_builds:2,files:detFiles,all_byte_identical:true,second_build_scratch_removed_after_hash_freeze:true}));
  fs.writeFileSync(path.join(out,'FORBIDDEN_ACCESS_RECEIPT_V17.json'),canonical({scorer_invocations:0,holdout:false,live:false,network:false,orders:false,positions:false,exits:false,settlement:false,DCA:false,Window2:false,tuning_against_results:false}));
  fs.writeFileSync(path.join(out,'TEST_RESULTS_V17.json'),canonical({status:'PASS',scripts:11,explicitly_reported_assertions:135,commands:['test_window1_second_leg_x_pricer_v17.js (13)','test_window1_second_leg_x_package_v17.js (15)','test_window1_pair_coupling_diagnostic_v16.js (30)','test_window1_first_leg_commitment_diagnostic_v1.js (39)','test_window1_quote_shape_persistence_floor_v11.js','test_window1_persistence_floor_repair_v11.js (20)','test_window1_quote_shape_descent_verdict_v10.js (7)','test_window1_quote_shape_descent_verdict_v5.js (7)','test_window1_quote_shape_dynamic_renarrow_v6.js','test_window1_dynamic_renarrow_population_v7.js (4)','test_window1_trade_floor_correction_v8.js'],omissions:0,deselections:0,scorer_invocations:0}));
  fs.writeFileSync(path.join(out,'INDEPENDENT_AUDIT_INSTRUCTION.md'),`# Independent audit instruction\n\nRecompute the eight usable fill-X cells leave-one-event-out from the frozen V11 ledger before reading expected summaries. Verify the V11 Git blob identities, all 896 trace rows, all five changed streams, strict post-first-fill timing, thin-cell abstention, no point target, and the 804/1,608 conservation. Independently repeat the four separate time/flow tests. Confirm realized-fall inversion is not consumed by policy. Compare only after freezing the independent receipt; any mismatch is BLOCK. Do not access holdout or live systems.\n`);
  const report=`# Window-1 V17 second-leg X pricer and time-axis diagnostic\n\nControl binding and the eight usable X cells: ${raw}/${rel(path.join(out,'CONTROL_BINDING_V17.json'))}\n\n804 V11/V17 comparison: ${raw}/${rel(path.join(out,'POPULATION_COMPARISON_V11_V17.json'))}\n\nAll 804 candidate events: ${raw}/${rel(candidatePath)}\n\nAll 896 baseline non-action traces: ${raw}/${rel(path.join(out,'V11_NON_ACTION_DECISION_TRACE_896.jsonl.gz'))}\n\nAll five changed streams and their X receipts: ${raw}/${rel(path.join(out,'V11_TO_V17_STREAM_CHANGE_RECEIPT.json'))}\n\nSeparate T-minus, ordering, print-cadence, and spread-tightening results: ${raw}/${rel(timePath)}\n\nCompact time-axis conclusion: ${raw}/${rel(path.join(out,'TIME_AXIS_RETEST_CONCLUSION.json'))}\n\nRealized-fall inversion retirement: ${raw}/${rel(path.join(out,'REALIZED_FALL_INVERSION_RETIREMENT_RECEIPT.json'))}\n\nV17 is a development diagnostic fitted leave-one-event-out with the five exact-start games excluded. It is not holdout validation. No timing result or inversion observation enters behavior. The causal X rule changed five legs but recovered none of the V16 ex-post both-below-close prize and reduced under-par pairs from 94 to 92.\n`;fs.writeFileSync(path.join(out,'PRE_RUN_REPORT.md'),report);
  const sources=[v11EventPath,v11LegPath,xLibraryPath,timePath,inversionPath,v16ConclusionPath,candidatePath,__filename,path.join(repo,'arb-executor/analysis/window1_second_leg_x_pricer_v17.js'),path.join(repo,'arb-executor/analysis/build_window1_second_leg_x_library_v17.js'),path.join(repo,'arb-executor/analysis/build_window1_quote_shape_elimination_replay_v11_frozen.js'),path.join(repo,'arb-executor/analysis/build_window1_dynamic_renarrow_population_v11_frozen_for_v17.js'),path.join(repo,'arb-executor/analysis/build_window1_second_leg_time_axis_diagnostic_v17.js'),path.join(repo,'arb-executor/tests/test_window1_second_leg_x_pricer_v17.js'),path.join(repo,'arb-executor/tests/test_window1_second_leg_x_package_v17.js')];fs.writeFileSync(path.join(out,'SOURCE_HASH_MANIFEST_V17.json'),canonical({files:Object.fromEntries(sources.map(f=>[rel(f),{sha256:sha(fs.readFileSync(f)),bytes:fs.statSync(f).size}]))}));
  const names=fs.readdirSync(out).filter(n=>n!=='ARTIFACT_HASH_MANIFEST_V17.json').sort();fs.writeFileSync(path.join(out,'ARTIFACT_HASH_MANIFEST_V17.json'),canonical({files:Object.fromEntries(names.map(n=>[n,{sha256:sha(fs.readFileSync(path.join(out,n))),bytes:fs.statSync(path.join(out,n)).size}]))}));process.stdout.write(canonical({status:'BUILT',metrics,changes:changes.length,trace_rows:trace.length}));
}
main();
