#!/usr/bin/env node
"use strict";

const crypto = require("crypto"), fs = require("fs"), path = require("path"), zlib = require("zlib");
const args = process.argv.slice(2), value = (name, fallback) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : fallback; };
const repo = path.resolve(value("--repo", "."));
const run1 = path.resolve(value("--run1", path.join(repo, ".claude/_v19_pair_candidate_run1/EVENT_LEDGER.jsonl.gz")));
const run2 = path.resolve(value("--run2", path.join(repo, ".claude/_v19_pair_candidate_run2/EVENT_LEDGER.jsonl.gz")));
const fit1 = path.resolve(value("--fit1", path.join(repo, ".claude/window1_live_v4_replay/pair_couple_v19_fit_20260803/PAIR_COUPLE_LIBRARY_V19.json")));
const fit2 = path.resolve(value("--fit2", path.join(repo, ".claude/_v19_pair_fit2/PAIR_COUPLE_LIBRARY_V19.json")));
const out = path.resolve(value("--output", path.join(repo, ".claude/window1_live_v4_replay/pair_couple_abstention_v19_20260803")));
const v11LegPath = path.join(repo, ".claude/window1_live_v4_replay/persistence_floor_repair_v11_20260802/POPULATION_LEG_LEDGER.jsonl.gz");
const v11EventPath = path.join(repo, ".claude/window1_live_v4_replay/persistence_floor_repair_v11_20260802/POPULATION_EVENT_LEDGER.jsonl.gz");
const v11FunnelPath = path.join(repo, ".claude/window1_live_v4_replay/persistence_floor_repair_v11_20260802/FUNNEL_AND_FIVE_CEILINGS.json");
const v11CarriedPath = path.join(repo, ".claude/window1_live_v4_replay/live_book_ordinal_root_repair_v15_20260803/CARRIED_PAIR_RECONCILIATION.json");
const raw = "https://raw.githubusercontent.com/OMIGROUPOPS/Omi-Workspace/refs/heads/codex/window1-live-consolidated";

function canonical(x) { return `${JSON.stringify(x, null, 2)}\n`; }
function sha256(x) { return crypto.createHash("sha256").update(x).digest("hex"); }
function hashFile(file) { return sha256(fs.readFileSync(file)); }
function ensure(x, message) { if (!x) throw new Error(message); }
function readRows(file) { const text = zlib.gunzipSync(fs.readFileSync(file)).toString("utf8").trim(); return text ? text.split(/\r?\n/).map(JSON.parse) : []; }
function gzipRows(rows) { return zlib.gzipSync(Buffer.from(`${rows.map(JSON.stringify).join("\n")}\n`), { level: 9, mtime: 0 }); }
function rel(file) { return path.relative(repo, file).replaceAll("\\", "/"); }
function group(rows, key) { const out = new Map(); for (const row of rows) { const k = key(row); if (!out.has(k)) out.set(k, []); out.get(k).push(row); } return out; }
function countBy(rows, key) { const out = {}; for (const row of rows) { const k = String(key(row)); out[k] = (out[k] || 0) + 1; } return Object.fromEntries(Object.entries(out).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))); }
function quantile(values, p) { const x = values.filter(Number.isFinite).sort((a, b) => a - b); return x.length ? x[Math.floor((x.length - 1) * p)] : null; }
function distribution(values) { const x = values.filter(Number.isFinite); return { denominator: values.length, numeric_n: x.length, censored_or_never_placed_n: values.length - x.length, min: x.length ? Math.min(...x) : null, p25: quantile(x, .25), median: quantile(x, .5), p75: quantile(x, .75), p90: quantile(x, .9), max: x.length ? Math.max(...x) : null, total_numeric_cents: x.reduce((sum, value) => sum + value, 0) }; }
function pairOnly(leg) { return Boolean(leg.placement?.pair_interim_v18?.resolved_by_pair_hypothesis_not_single_leg_hypothesis && leg.placement?.pair_interim_v18?.pair_couple_ids?.length); }

function baselineLeg(old) {
  return { ...old, proposed_entry_cents: old.acted ? old.entry_cents : null, honest_credited_entry_cents: old.credited ? old.entry_cents : null, delta_to_own_window1_close_cents: old.entry_minus_own_window1_close_cents, delta_to_own_ask_reachable_low_cents: old.entry_minus_qualifying_ask_floor_cents, source_lane: "FROZEN_V11_BASE", pair_couple_added: false, pair_couple_receipt: null };
}
function addedLeg(old, candidate) {
  return { ...old, ...candidate, leg_identity: old.leg_identity, objective_traded_low_cents: old.objective_traded_low_cents, traded_low_proof: old.traded_low_proof, qualifying_ask_floor_cents: old.qualifying_ask_floor_cents, own_window1_close_cents: old.own_window1_close_cents, close_status: old.close_status, close_seconds_before_guarded_right: old.close_seconds_before_guarded_right, acted: candidate.proposed_entry_cents !== null, credited: candidate.honest_credited_entry_cents !== null, entry_cents: candidate.honest_credited_entry_cents, entry_minus_qualifying_ask_floor_cents: candidate.honest_credited_entry_cents === null || !Number.isInteger(old.qualifying_ask_floor_cents) ? null : candidate.honest_credited_entry_cents - old.qualifying_ask_floor_cents, entry_minus_objective_traded_low_cents: candidate.honest_credited_entry_cents === null || !Number.isInteger(old.objective_traded_low_cents) ? null : candidate.honest_credited_entry_cents - old.objective_traded_low_cents, entry_minus_own_window1_close_cents: candidate.honest_credited_entry_cents === null || !Number.isInteger(old.own_window1_close_cents) ? null : candidate.honest_credited_entry_cents - old.own_window1_close_cents, source_lane: "PAIR_COUPLE_V19_ADDITION_TO_V11_NON_ACTION", pair_couple_added: true, pair_couple_receipt: candidate.placement.pair_interim_v18 };
}
function eventMetrics(events) {
  const legs = events.flatMap((event) => Object.values(event.legs)), completed = events.filter((event) => event.completed_pair);
  return { D: events.length, legs: legs.length, acted_legs: legs.filter((leg) => leg.acted).length, credited_legs: legs.filter((leg) => leg.credited).length, completed_pairs: completed.length, pairs_under_par: events.filter((event) => event.pair_under_par).length, both_legs_strictly_below_close: events.filter((event) => event.both_legs_strictly_below_close).length, execution_floor_pair_pass: events.filter((event) => event.execution_floor_pair_pass).length, strict_carried_pairs: completed.filter((event) => { const ds = Object.values(event.legs).map((leg) => leg.entry_minus_own_window1_close_cents); return ds.some((x) => x > 0) && ds.some((x) => x < 0); }).length };
}
function frontier(events) {
  const tiers = { LE_93: (x) => x <= 93, LE_95: (x) => x <= 95, LE_97: (x) => x <= 97, LT_100: (x) => x < 100, ANY_PRICE: () => true }, out = {};
  for (const [name, predicate] of Object.entries(tiers)) { const rows = events.filter((event) => event.completed_pair && predicate(event.combined_entry_cents)); out[name] = { denominator: events.length, completed_pairs: rows.length, raw_rate: `${rows.length}/${events.length}`, pairs_both_legs_strictly_below_close: rows.filter((event) => event.both_legs_strictly_below_close).length }; }
  out.any_price_reference_ceiling = { denominator: events.length, count: events.filter((event) => event.take_ceiling_member).length, law: "FROZEN_516_TAKE_REACHABLE_REFERENCE_CEILING; NOT A POLICY FILL" };
  return out;
}
function regretBucket(leg) {
  if (!Number.isInteger(leg.objective_traded_low_cents)) return "PRINT_BACKED_FLOOR_UNAVAILABLE";
  if (!leg.credited) return "NEVER_PLACED_FULL_REGRET";
  const gap = leg.entry_cents - leg.objective_traded_low_cents;
  return gap < 0 ? "BETTER_THAN_PRINT_FLOOR" : gap === 0 ? "ZERO" : gap <= 3 ? "ONE_TO_THREE" : gap <= 9 ? "FOUR_TO_NINE" : "TEN_OR_MORE";
}
function regretRow(leg) {
  const numeric = leg.credited && Number.isInteger(leg.objective_traded_low_cents) ? leg.entry_cents - leg.objective_traded_low_cents : null;
  return { leg_identity: leg.leg_identity, event_id: leg.event_id, category: leg.category, price_region: leg.price_region, source_lane: leg.source_lane, credited_fill_cents: leg.credited ? leg.entry_cents : null, achievable_print_backed_floor_cents: leg.objective_traded_low_cents, regret_cents: numeric, never_placed_carries_full_regret: !leg.credited, full_regret_representation: !leg.credited ? "CATEGORICAL_FULL_LOSS_WITH_FLOOR_PRESERVED; NO_FABRICATED_FILL_PRICE" : null, loss_bucket: regretBucket(leg), loss_attribution: leg.credited ? leg.source_lane : `NEVER_PLACED:${leg.terminal_reason || "NO_ACTION"}` };
}
function stopLevel(reason) { if (reason === "SOURCE_UNAVAILABLE") return "SOURCE"; if (String(reason).includes("PAIR_TUPLE")) return "PAIR_MICRO"; if (String(reason).includes("SHAPE") || String(reason).includes("LOWER")) return "SINGLE_LEG_MACRO_OR_MICRO_ORDINAL"; if (String(reason).includes("MICRO")) return "MICRO_MICRO"; return "OTHER_NAMED"; }

function main() {
  for (const file of [run1, run2, fit1, fit2, v11LegPath, v11EventPath, v11FunnelPath, v11CarriedPath]) ensure(fs.existsSync(file), `missing ${file}`);
  ensure(hashFile(run1) === hashFile(run2), "candidate population builds differ"); ensure(hashFile(fit1) === hashFile(fit2), "couple library builds differ");
  const candidateEvents = readRows(run1), candidateLegs = new Map(candidateEvents.flatMap((event) => Object.values(event.legs).map((leg) => [`${event.event_id}|${leg.leg_id}`, leg]))), oldLegs = readRows(v11LegPath), oldEvents = readRows(v11EventPath), v11Funnel = JSON.parse(fs.readFileSync(v11FunnelPath)), v11Carried = JSON.parse(fs.readFileSync(v11CarriedPath)), library = JSON.parse(fs.readFileSync(fit1));
  ensure(candidateEvents.length === 804 && oldEvents.length === 804 && oldLegs.length === 1608, "population conservation");
  const finalLegs = oldLegs.map((old) => { const candidate = candidateLegs.get(old.leg_identity); ensure(candidate, `missing candidate ${old.leg_identity}`); return !old.acted && pairOnly(candidate) ? addedLeg(old, candidate) : baselineLeg(old); });
  const finalByKey = new Map(finalLegs.map((leg) => [leg.leg_identity, leg]));
  const oldEventById = new Map(oldEvents.map((event) => [event.event_id, event]));
  const finalEvents = candidateEvents.map((candidateEvent) => {
    const oldEvent = oldEventById.get(candidateEvent.event_id), legs = Object.fromEntries(Object.keys(candidateEvent.legs).sort().map((legId) => [legId, finalByKey.get(`${candidateEvent.event_id}|${legId}`)]));
    const xs = Object.values(legs), completed = xs.every((leg) => leg.credited), combined = completed ? xs.reduce((sum, leg) => sum + leg.entry_cents, 0) : null;
    return { event_id: candidateEvent.event_id, category: candidateEvent.category, starting_price_split: candidateEvent.starting_price_split, legs, completed_pair: completed, combined_entry_cents: combined, pair_under_par: completed && combined < 100, both_legs_strictly_below_close: completed && xs.every((leg) => Number.isInteger(leg.own_window1_close_cents) && leg.entry_cents < leg.own_window1_close_cents), execution_floor_pair_pass: completed && combined < 100 && xs.every((leg) => Number.isInteger(leg.qualifying_ask_floor_cents) && leg.entry_cents <= leg.qualifying_ask_floor_cents), take_ceiling_member: candidateEvent.take_ceiling_member, maker_ceiling_member: candidateEvent.maker_ceiling_member, pair_couple_added_legs: xs.filter((leg) => leg.pair_couple_added).map((leg) => leg.leg_id), V11_completed_pair: oldEvent.completed_pair };
  }).sort((a, b) => a.event_id.localeCompare(b.event_id));
  const v11 = { D: 804, legs: 1608, acted_legs: oldLegs.filter((leg) => leg.acted).length, credited_legs: oldLegs.filter((leg) => leg.credited).length, completed_pairs: oldEvents.filter((event) => event.completed_pair).length, pairs_under_par: oldEvents.filter((event) => event.pair_under_par).length, both_legs_strictly_below_close: oldEvents.filter((event) => event.both_legs_strictly_below_close).length, execution_floor_pair_pass: v11Funnel.full_population.execution_floor_pair_pass, strict_carried_pairs: v11Carried.strict_one_above_one_below_rows_diagnosed };
  ensure(JSON.stringify([v11.acted_legs,v11.completed_pairs,v11.pairs_under_par,v11.both_legs_strictly_below_close,v11.execution_floor_pair_pass,v11.strict_carried_pairs]) === JSON.stringify([712,185,94,21,29,52]), "V11 floor mismatch");
  const current = eventMetrics(finalEvents); for (const key of ["acted_legs","completed_pairs","pairs_under_par","both_legs_strictly_below_close","execution_floor_pair_pass"]) ensure(current[key] >= v11[key], `abstention floor violated ${key}`);
  const partitions = [...group(finalEvents, (event) => `${event.category}|${event.starting_price_split}`)].sort(([a], [b]) => a.localeCompare(b)).map(([key, rows]) => ({ category: key.split("|")[0], starting_price_region: key.split("|")[1], D: rows.length, metrics: eventMetrics(rows), frontier: frontier(rows) }));
  const comparison = { schema_version: "WINDOW1_PAIR_COUPLE_ABSTENTION_V19_COMPARISON", score_free: true, V11: v11, V19: current, delta: Object.fromEntries(Object.keys(v11).filter((key) => Number.isInteger(v11[key])).map((key) => [key, current[key] - v11[key]])), abstention_floor_pass: true, frontier: frontier(finalEvents), category_and_starting_price_region: partitions, claim: "IN_SAMPLE DEVELOPMENT REPLAY; NOT HOLDOUT; NOT MARKET CEILING" };
  const regrets = finalLegs.map(regretRow), regretCells = [...group(regrets, (row) => `${row.category}|${row.price_region}|${row.loss_bucket}`)].sort(([a], [b]) => a.localeCompare(b)).map(([key, rows]) => ({ category: key.split("|")[0], price_region: key.split("|")[1], loss_bucket: key.split("|")[2], n: rows.length, regret_distribution: distribution(rows.map((row) => row.regret_cents)), loss_attribution: countBy(rows, (row) => row.loss_attribution), never_placed_full_regret_n: rows.filter((row) => row.never_placed_carries_full_regret).length }));
  const regretGauge = { schema_version: "WINDOW1_PAIR_COUPLE_V19_REGRET_GAUGE", law: "REGRET = CREDITED FILL - ACHIEVABLE PRINT-BACKED FLOOR", denominator_legs: 1608, numeric_completed_regret: distribution(regrets.map((row) => row.regret_cents)), never_placed_full_regret_n: regrets.filter((row) => row.never_placed_carries_full_regret).length, never_placed_law: "INCLUDED IN DENOMINATOR AND LOSS ATTRIBUTION; FLOOR PRESERVED; NO FABRICATED FILL PRICE OR 100-CENT PENALTY", category_price_region_loss_buckets: regretCells };
  const oldNonActions = oldLegs.filter((leg) => !leg.acted), trace = oldNonActions.map((old) => { const now = finalByKey.get(old.leg_identity); return { leg_identity: old.leg_identity, event_id: old.event_id, category: old.category, price_region: old.price_region, V11_terminal_reason: old.terminal_reason, V19_acted: now.acted, V19_entry_cents: now.entry_cents, resolved_by_pair_couple_only: now.pair_couple_added, pair_couple_receipt: now.pair_couple_receipt, final_stop_level: now.acted ? "ACTED" : stopLevel(old.terminal_reason), final_terminal_reason: now.acted ? "PAIR_COUPLE_RESOLVED_SINGLE_LEG_AMBIGUITY" : old.terminal_reason } });
  const traceCells = [...group(trace, (row) => `${row.category}|${row.price_region}`)].sort(([a], [b]) => a.localeCompare(b)).map(([key, rows]) => ({ category: key.split("|")[0], price_region: key.split("|")[1], V11_non_actions: rows.length, resolved_by_pair_couple_only: rows.filter((row) => row.resolved_by_pair_couple_only).length, still_stopped: rows.filter((row) => !row.V19_acted).length, stop_levels: countBy(rows.filter((row) => !row.V19_acted), (row) => row.final_stop_level), reasons: countBy(rows.filter((row) => !row.V19_acted), (row) => row.final_terminal_reason) }));
  const traceCensus = { schema_version: "WINDOW1_V11_896_PAIR_COUPLE_V19_TRACE", denominator: trace.length, resolved_by_pair_hypothesis_no_single_leg_hypothesis_could_resolve: trace.filter((row) => row.resolved_by_pair_couple_only).length, still_stopped: trace.filter((row) => !row.V19_acted).length, former_V18_joint_macro_veto_count: 0, abstention_fallback: "FROZEN_V11", category_and_price_region: traceCells };
  fs.mkdirSync(out, { recursive: true }); fs.copyFileSync(fit1, path.join(out, "PAIR_COUPLE_LIBRARY_V19.json")); fs.writeFileSync(path.join(out, "POPULATION_EVENT_LEDGER.jsonl.gz"), gzipRows(finalEvents)); fs.writeFileSync(path.join(out, "POPULATION_LEG_LEDGER.jsonl.gz"), gzipRows(finalLegs)); fs.writeFileSync(path.join(out, "FRONTIER.json"), canonical({ fixed_denominator: 804, tiers: frontier(finalEvents), category_and_starting_price_region: partitions.map((row) => ({ category: row.category, starting_price_region: row.starting_price_region, D: row.D, frontier: row.frontier })) })); fs.writeFileSync(path.join(out, "REGRET_LEG_LEDGER.jsonl.gz"), gzipRows(regrets)); fs.writeFileSync(path.join(out, "REGRET_GAUGE.json"), canonical(regretGauge)); fs.writeFileSync(path.join(out, "V11_896_PAIR_COUPLE_RESOLUTION_TRACE.jsonl.gz"), gzipRows(trace));
  for (const [name, object] of [["V11_COMPARISON.json", comparison], ["NON_ACTION_RESOLUTION_CENSUS.json", traceCensus], ["PAIR_COUPLE_CENSUS.json", { architecture: library.architecture, census: library.census, categories: Object.fromEntries(Object.entries(library.pair_couple_groups).map(([category, group]) => [category, { minimum_n: group.minimum_n, couples: group.couples.map((row) => ({ pair_couple_id: row.pair_couple_id, n: row.n, authority: row.authority, usable_for_signing: row.usable_for_signing, borrowed_from: row.borrowed_from, direct_coherence: row.direct_receipt, borrowed_parent_receipt: row.borrowed_parent_receipt })) }])) }], ["V18_RULING_CORRECTION_RECEIPT.json", { V18_conclusion: "RETRACTED", violations: ["CATEGORY_MONOLITHS_NOT_LEG_SHAPE_COUPLES", "UNSIGNABLE_PAIR_LAYER_VETOED_SINGLE_LEG_PATH"], V18_artifacts_preserved: true, V19_correction: "EXACT_COUPLES_WITH_EXPLICIT_PARENT_BORROW_AND_ABSTENTION_TO_FROZEN_V11" }], ["DETERMINISM_RECEIPT.json", { couple_library_builds: 2, fit1_sha256: hashFile(fit1), fit2_sha256: hashFile(fit2), fits_byte_identical: true, candidate_replays: 2, run1_sha256: hashFile(run1), run2_sha256: hashFile(run2), candidate_replays_byte_identical: true, final_overlay_is_pure_deterministic_transform: true }], ["FORBIDDEN_ACCESS_RECEIPT.json", { scorer_invocations: 0, holdout: false, live: false, network: false, orders: false, positions: false, exits: false, settlement: false, DCA: false, Window2: false, forecast: false, fee_test: false }]]) fs.writeFileSync(path.join(out, name), canonical(object));
  fs.writeFileSync(path.join(out, "TEST_RESULTS.json"), canonical({ status: "PASS", files_run: ["arb-executor/tests/test_window1_pair_couple_elimination_v19.js", "arb-executor/tests/test_window1_pair_couple_v19_package.js", "arb-executor/tests/test_window1_pair_interim_elimination_v18.js", "arb-executor/tests/test_window1_interim_elimination_v13.js", "arb-executor/tests/test_window1_interim_micro_repair_v14.js", "arb-executor/tests/test_window1_quote_shape_persistence_floor_v11.js"], files_passed: 6, files_failed: 0, omissions: 0, scorer_invocations: 0, holdout_access: false, live_access: false }));
  fs.writeFileSync(path.join(out, "INDEPENDENT_AUDIT_INSTRUCTION.md"), "# Independent audit\n\nRebuild the 69 exact V13 interim-shape couples before reading expected totals. Verify the July-6 n>=30 law, exact-to-parent borrowed_from receipts, no category monolith, no silent interpolation, unusable-couple abstention, byte-identical V11 fallback, frontier tiers on D=804, regret denominators including categorical full loss for never-placed legs without fabricated fill prices, and the exact 896-row trace. Freeze independent counts before comparison. Any mismatch is BLOCK.\n");
  const url = (name) => `${raw}/${rel(path.join(out, name))}`;
  fs.writeFileSync(path.join(out, "PRE_RUN_REPORT.md"), `# Window-1 pair-couple V19\n\nV18 is retracted. V19 enumerates exact couples of the 39 V13 interim leg hypotheses. Thin couples use only explicit coherent n>=30 structural parents; otherwise they abstain to frozen V11.\n\n- Couples: ${url("PAIR_COUPLE_CENSUS.json")}\n- V11 comparison and partitioned frontier: ${url("V11_COMPARISON.json")}\n- Ratified frontier: ${url("FRONTIER.json")}\n- Regret gauge: ${url("REGRET_GAUGE.json")}\n- 896 trace: ${url("NON_ACTION_RESOLUTION_CENSUS.json")}\n- Exact trace ledger: ${url("V11_896_PAIR_COUPLE_RESOLUTION_TRACE.jsonl.gz")}\n- Vault restoration addendum: ${raw}/arb-executor/docs/research/window1/WINDOW1_PAIR_COUPLE_V19_VAULT_ADDENDUM.md\n`);
  const sources = [fit1, path.join(out, "POPULATION_EVENT_LEDGER.jsonl.gz"), v11LegPath, v11EventPath, v11FunnelPath, v11CarriedPath, path.join(repo, "arb-executor/analysis/build_window1_pair_couple_library_v19.js"), path.join(repo, "arb-executor/analysis/window1_pair_couple_elimination_v19.js"), path.join(repo, "arb-executor/analysis/build_window1_quote_shape_elimination_replay_v1.js"), path.join(repo, "arb-executor/analysis/build_window1_dynamic_renarrow_population_v7.js"), __filename, path.join(repo, "arb-executor/tests/test_window1_pair_couple_elimination_v19.js"), path.join(repo, "arb-executor/tests/test_window1_pair_couple_v19_package.js"), path.join(repo, "arb-executor/docs/research/window1/WINDOW1_PAIR_COUPLE_V19_VAULT_ADDENDUM.md"), path.join(repo, "arb-executor/docs/LIVING_VAULT.md"), path.join(repo, ".claude/HANDOFF_FABLE.md")]; fs.writeFileSync(path.join(out, "SOURCE_HASH_MANIFEST.json"), canonical({ files: Object.fromEntries(sources.map((file) => [rel(file), { sha256: hashFile(file), bytes: fs.statSync(file).size }])) }));
  const names = fs.readdirSync(out).filter((name) => name !== "ARTIFACT_HASH_MANIFEST.json").sort(); fs.writeFileSync(path.join(out, "ARTIFACT_HASH_MANIFEST.json"), canonical({ files: Object.fromEntries(names.map((name) => [name, { sha256: hashFile(path.join(out, name)), bytes: fs.statSync(path.join(out, name)).size }])) }));
  process.stdout.write(canonical({ status: "BUILT", comparison, trace_census: traceCensus, library_census: library.census }));
}
main();
