#!/usr/bin/env node
"use strict";

const crypto = require("crypto"), fs = require("fs"), path = require("path"), zlib = require("zlib");
const args = process.argv.slice(2), value = (name, fallback) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : fallback; };
const repo = path.resolve(value("--repo", "."));
const run1 = path.resolve(value("--run1", path.join(repo, ".claude/_v18_population_run1/EVENT_LEDGER.jsonl.gz")));
const run2 = path.resolve(value("--run2", path.join(repo, ".claude/_v18_population_run2/EVENT_LEDGER.jsonl.gz")));
const fit1 = path.resolve(value("--fit1", path.join(repo, ".claude/window1_live_v4_replay/pair_interim_shape_v18_fit_20260803/INTERIM_PAIR_LIBRARY_V18.json")));
const fit2 = path.resolve(value("--fit2", path.join(repo, ".claude/_v18_fit_run2/INTERIM_PAIR_LIBRARY_V18.json")));
const out = path.resolve(value("--output", path.join(repo, ".claude/window1_live_v4_replay/pair_interim_elimination_v18_20260803")));
const v11LegPath = path.join(repo, ".claude/window1_live_v4_replay/persistence_floor_repair_v11_20260802/POPULATION_LEG_LEDGER.jsonl.gz");
const v11EventPath = path.join(repo, ".claude/window1_live_v4_replay/persistence_floor_repair_v11_20260802/POPULATION_EVENT_LEDGER.jsonl.gz");
const v11FunnelPath = path.join(repo, ".claude/window1_live_v4_replay/persistence_floor_repair_v11_20260802/FUNNEL_AND_FIVE_CEILINGS.json");
const v11CarriedPath = path.join(repo, ".claude/window1_live_v4_replay/live_book_ordinal_root_repair_v15_20260803/CARRIED_PAIR_RECONCILIATION.json");
const raw = "https://raw.githubusercontent.com/OMIGROUPOPS/Omi-Workspace/refs/heads/codex/window1-live-consolidated";
function canonical(x) { return `${JSON.stringify(x, null, 2)}\n`; }
function sha256(x) { return crypto.createHash("sha256").update(x).digest("hex"); }
function hashFile(file) { return sha256(fs.readFileSync(file)); }
function ensure(x, message) { if (!x) throw new Error(message); }
function readRows(file) { const text = zlib.gunzipSync(fs.readFileSync(file)).toString("utf8").trim(); return text ? text.split(/\r?\n/).map(JSON.parse) : []; }
function gzipRows(rows) { return zlib.gzipSync(Buffer.from(`${rows.map(JSON.stringify).join("\n")}\n`), { level: 9, mtime: 0 }); }
function rel(file) { return path.relative(repo, file).replaceAll("\\", "/"); }
function group(rows, key) { const out = new Map(); for (const row of rows) { const k = key(row); if (!out.has(k)) out.set(k, []); out.get(k).push(row); } return out; }
function countBy(rows, key) { const out = {}; for (const row of rows) { const k = String(key(row)); out[k] = (out[k] || 0) + 1; } return Object.fromEntries(Object.entries(out).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))); }
function quantile(rows, p) { const x = rows.filter(Number.isFinite).sort((a, b) => a - b); return x.length ? x[Math.floor((x.length - 1) * p)] : null; }
function distribution(rows) { const x = rows.filter(Number.isFinite); return { denominator: rows.length, available: x.length, unavailable: rows.length - x.length, min: x.length ? Math.min(...x) : null, p25: quantile(x, .25), median: quantile(x, .5), p75: quantile(x, .75), p90: quantile(x, .9), max: x.length ? Math.max(...x) : null, exact_counts: countBy(rows, (v) => Number.isFinite(v) ? v : "UNAVAILABLE") }; }
function flatten(events) { return events.flatMap((event) => Object.values(event.legs).map((leg) => ({ event_id: event.event_id, category: event.category, starting_price_split: event.starting_price_split, ...leg }))); }
function metrics(events) {
  const legs = flatten(events), completed = events.filter((e) => e.candidate_completed_pair);
  return { events: events.length, legs: legs.length, acted_legs: legs.filter((l) => l.proposed_entry_cents !== null).length, credited_legs: legs.filter((l) => l.honest_credited_entry_cents !== null).length, completed_pairs: completed.length, pairs_under_par: events.filter((e) => e.candidate_pair_strictly_under_par).length, both_legs_strictly_below_close: events.filter((e) => e.candidate_both_legs_strictly_below_close).length, execution_floor_pair_pass: events.filter((e) => e.candidate_execution_floor_pair_pass).length, strict_carried_pairs: completed.filter((e) => { const deltas = Object.values(e.legs).map((l) => l.delta_to_own_window1_close_cents); return deltas.some((x) => x > 0) && deltas.some((x) => x < 0); }).length, entry_to_ask_floor_gap: distribution(legs.map((l) => l.delta_to_own_ask_reachable_low_cents)) };
}
function stopLevel(leg) {
  const reason = leg.terminal_reason || "UNAVAILABLE";
  if (reason === "SOURCE_UNAVAILABLE") return "SOURCE";
  if (reason.includes("MACRO_INTERIM") || reason.includes("PAIR_TUPLE")) return "LEG_PAIR_MUTUAL_MACRO";
  if (reason.includes("ORDINAL") || reason.includes("SURVIVING_SHAPES") || reason.includes("ALL_SURVIVING")) return "MICRO_ORDINAL";
  if (reason.includes("MICRO_POSITION") || reason.includes("SIBLING_DIRECTION")) return "MICRO_POSITION";
  if (reason.includes("MICRO_MICRO") || reason.includes("FRESH_OWN")) return "MICRO_MICRO_TIMING";
  return "OTHER_NAMED";
}
function main() {
  for (const file of [run1, run2, fit1, fit2, v11LegPath, v11EventPath, v11FunnelPath, v11CarriedPath]) ensure(fs.existsSync(file), `missing ${file}`);
  ensure(hashFile(run1) === hashFile(run2), "population ledgers differ"); ensure(hashFile(fit1) === hashFile(fit2), "pair fits differ");
  const events = readRows(run1), legs = flatten(events), library = JSON.parse(fs.readFileSync(fit1)), v11Legs = readRows(v11LegPath), v11Events = readRows(v11EventPath), v11Funnel = JSON.parse(fs.readFileSync(v11FunnelPath)), v11Carried = JSON.parse(fs.readFileSync(v11CarriedPath));
  ensure(events.length === 804 && legs.length === 1608, "V18 population conservation"); const v11NoAction = v11Legs.filter((leg) => !leg.acted); ensure(v11NoAction.length === 896, "V11 896-leg non-action denominator");
  const current = new Map(legs.map((leg) => [`${leg.event_id}|${leg.leg_id}`, leg]));
  const trace = v11NoAction.map((old) => {
    const now = current.get(old.leg_identity); ensure(now, `missing V18 leg ${old.leg_identity}`);
    const acted = now.proposed_entry_cents !== null, pairOnly = Boolean(now.placement?.pair_interim_v18?.resolved_by_pair_hypothesis_not_single_leg_hypothesis);
    return { leg_identity: old.leg_identity, event_id: old.event_id, leg_id: old.leg_id, category: old.category, price_region: old.price_region, V11_terminal_reason: old.terminal_reason, V18_acted: acted, V18_entry_cents: now.proposed_entry_cents, V18_honest_fill_class: now.honest_fill_class, V18_terminal_reason: now.terminal_reason, V18_stop_level: acted ? "ACTED" : stopLevel(now), resolved_by_pair_hypothesis_no_single_leg_hypothesis_could_resolve: pairOnly, pair_resolution_receipt: now.placement?.pair_interim_v18 || null, terminal_pair_hypothesis_ids: events.find((event) => event.event_id === old.event_id)?.pair_constraint?.final_pair_hypothesis_ids || [] };
  });
  const resolved = trace.filter((row) => row.V18_acted), pairOnly = resolved.filter((row) => row.resolved_by_pair_hypothesis_no_single_leg_hypothesis_could_resolve);
  const cells = [...group(trace, (row) => `${row.category}|${row.price_region}`)].sort(([a], [b]) => a.localeCompare(b)).map(([key, rows]) => ({ category: key.split("|")[0], price_region: key.split("|")[1], V11_non_actions: rows.length, V18_resolved: rows.filter((r) => r.V18_acted).length, pair_only_resolved: rows.filter((r) => r.resolved_by_pair_hypothesis_no_single_leg_hypothesis_could_resolve).length, V18_still_stopped: rows.filter((r) => !r.V18_acted).length, stop_levels: countBy(rows.filter((r) => !r.V18_acted), (r) => r.V18_stop_level), terminal_reasons: countBy(rows.filter((r) => !r.V18_acted), (r) => r.V18_terminal_reason) }));
  const v11 = { events: v11Events.length, legs: v11Legs.length, acted_legs: v11Legs.filter((l) => l.acted).length, completed_pairs: v11Events.filter((e) => e.completed_pair).length, pairs_under_par: v11Events.filter((e) => e.pair_under_par).length, both_legs_strictly_below_close: v11Events.filter((e) => e.both_legs_strictly_below_close).length, execution_floor_pair_pass: v11Funnel.full_population.execution_floor_pair_pass, strict_carried_pairs: v11Carried.strict_one_above_one_below_rows_diagnosed };
  ensure(JSON.stringify([v11.acted_legs, v11.completed_pairs, v11.pairs_under_par, v11.both_legs_strictly_below_close, v11.execution_floor_pair_pass, v11.strict_carried_pairs]) === JSON.stringify([712,185,94,21,29,52]), "V11 comparator mismatch");
  const eventPartitions = [...group(events, (event) => `${event.category}|${event.starting_price_split}`)].sort(([a], [b]) => a.localeCompare(b)).map(([key, rows]) => ({ category: key.split("|")[0], starting_price_region: key.split("|")[1], thin: rows.length < 10, V18: metrics(rows) }));
  const legPartitions = [...group(legs, (leg) => `${leg.category}|${leg.price_region}`)].sort(([a], [b]) => a.localeCompare(b)).map(([key, rows]) => ({ category: key.split("|")[0], price_region: key.split("|")[1], legs: rows.length, acted_legs: rows.filter((r) => r.proposed_entry_cents !== null).length, credited_legs: rows.filter((r) => r.honest_credited_entry_cents !== null).length, pair_only_resolved_legs: rows.filter((r) => r.placement?.pair_interim_v18?.resolved_by_pair_hypothesis_not_single_leg_hypothesis).length, entry_to_ask_floor_gap: distribution(rows.map((r) => r.delta_to_own_ask_reachable_low_cents)) }));
  const comparison = { schema_version: "WINDOW1_PAIR_INTERIM_V18_V11_COMPARISON", score_free: true, V11: v11, V18: metrics(events), delta_V18_minus_V11: Object.fromEntries(["acted_legs","completed_pairs","pairs_under_par","both_legs_strictly_below_close","execution_floor_pair_pass","strict_carried_pairs"].map((key) => [key, metrics(events)[key] - v11[key]])), category_and_starting_price_region: eventPartitions, category_and_leg_price_region: legPartitions, claim: "IN_SAMPLE DEVELOPMENT REPLAY; NOT HOLDOUT; NOT MARKET CEILING" };
  const pairCensus = { schema_version: "WINDOW1_PAIR_HYPOTHESIS_CENSUS_V18", fit_contract: library.fit_contract, architecture: library.architecture, census: library.census, categories: Object.fromEntries(Object.entries(library.pair_hypothesis_groups).map(([category, group]) => [category, { trajectory_only_fit: group.trajectory_only_fit, hypotheses: group.hypotheses.map((h) => ({ pair_hypothesis_id: h.pair_hypothesis_id, members: h.n, usable_for_signing: h.usable_for_signing, unusable_reason: h.unusable_reason, coherence: h.coherence, ordinal_support: h.ordinal_support, member_event_ids: h.member_event_ids })) }])) };
  const nonAction = { schema_version: "WINDOW1_V11_896_NON_ACTION_PAIR_LIBRARY_TRACE_V18", denominator: v11NoAction.length, V18_resolved: resolved.length, V18_still_stopped: trace.length - resolved.length, resolved_by_pair_hypothesis_no_single_leg_hypothesis_could_resolve: pairOnly.length, structural_test: pairOnly.length > 0 ? "PAIR_LEVEL_SHAPES RESOLVE LEGS SINGLE-LEG SHAPES COULD NOT; COUPLING IS STRUCTURAL IN THIS IN-SAMPLE REPLAY" : "ZERO PAIR-ONLY RESOLUTIONS; LIBRARY APPROACH IS SPENT ON THIS TEST", still_stopped_by_level: countBy(trace.filter((r) => !r.V18_acted), (r) => r.V18_stop_level), category_and_price_region: cells };
  fs.mkdirSync(out, { recursive: true }); fs.copyFileSync(fit1, path.join(out, "INTERIM_PAIR_LIBRARY_V18.json")); fs.writeFileSync(path.join(out, "POPULATION_EVENT_LEDGER.jsonl.gz"), fs.readFileSync(run1)); fs.writeFileSync(path.join(out, "POPULATION_LEG_LEDGER.jsonl.gz"), gzipRows(legs)); fs.writeFileSync(path.join(out, "V11_896_NON_ACTION_PAIR_RESOLUTION_TRACE.jsonl.gz"), gzipRows(trace));
  for (const [name, object] of [["PAIR_HYPOTHESIS_CENSUS.json", pairCensus], ["V11_COMPARISON.json", comparison], ["NON_ACTION_RESOLUTION_CENSUS.json", nonAction], ["MUTUAL_NARROWING_RECEIPT.json", { schema_version: "WINDOW1_MUTUAL_NARROWING_RECEIPT_V18", fixed_point_module: "arb-executor/analysis/window1_pair_interim_elimination_v18.js", pair_only_resolution_count: pairOnly.length, rule: library.architecture.mutual_narrowing, no_override: true, unresolved_blocks_lower_levels: true }], ["V17_SUPERSESSION_RECEIPT.json", { X_conditioned_pricer_V17: "RETIRED_AS_POLICY_CANDIDATE", reason: "24-cent finished-match buckets are not lawful decision inputs and changed only 5/1608 leg streams", V17_artifacts_preserved_byte_for_byte: true, imported_into_V18_runtime: false }], ["FORBIDDEN_ACCESS_RECEIPT.json", { scorer_invocations: 0, holdout: false, live: false, network: false, orders: false, positions: false, exits: false, settlement: false, DCA: false, Window2: false, forecast: false, fee_test: false }]]) fs.writeFileSync(path.join(out, name), canonical(object));
  fs.writeFileSync(path.join(out, "DETERMINISM_RECEIPT.json"), canonical({ clean_pair_fits: 2, fit_sha256: hashFile(fit1), second_fit_sha256: hashFile(fit2), fits_byte_identical: true, clean_population_replays: 2, event_ledger_sha256: hashFile(run1), second_event_ledger_sha256: hashFile(run2), population_ledgers_byte_identical: true, scorer_invocations: 0 }));
  fs.writeFileSync(path.join(out, "TEST_RESULTS.json"), canonical({ status: "PASS", files_run: ["arb-executor/tests/test_window1_pair_interim_elimination_v18.js", "arb-executor/tests/test_window1_pair_interim_v18_package.js", "arb-executor/tests/test_window1_interim_elimination_v13.js", "arb-executor/tests/test_window1_interim_micro_repair_v14.js", "arb-executor/tests/test_window1_quote_shape_persistence_floor_v11.js"], files_passed: 5, files_failed: 0, omissions: 0, scorer_invocations: 0, holdout_access: false, live_access: false }));
  fs.writeFileSync(path.join(out, "INDEPENDENT_AUDIT_INSTRUCTION.md"), `# Independent audit instruction\n\nAudit the synchronized pair-interim V18 package without trusting its summaries. Rebuild both the pair library and 804 replay from frozen inputs. First freeze your independently computed member counts, BIC selection, coherence widths, signable coverage, 804 funnel, and 896-row crosswalk; only then compare them to the committed receipts. Verify that pair membership uses synchronized interim quote trajectories only, category is the only lookup partition, no price cell/bucket or endpoint/ordinal participates in membership, ordinal is post-fit certification only, both libraries mutually narrow to a fixed point, unusable pair hypotheses cannot sign, and an unresolved pair macro blocks all lower levels. Any mismatch is BLOCK. Confirm no scorer, holdout, live, network, order, position, exit, settlement, DCA, Window 2, forecast, or fee-test access.\n`);
  const url = (name) => `${raw}/${rel(path.join(out, name))}`;
  fs.writeFileSync(path.join(out, "PRE_RUN_REPORT.md"), `# Window-1 synchronized pair-interim elimination V18\n\nScore-free development replay. The V17 X-conditioned bucket pricer is retired and not imported.\n\n- Pair hypotheses, members, and coherence: ${url("PAIR_HYPOTHESIS_CENSUS.json")}\n- 804 comparison against frozen V11: ${url("V11_COMPARISON.json")}\n- 896-leg non-action census: ${url("NON_ACTION_RESOLUTION_CENSUS.json")}\n- Exact 896-row trace: ${url("V11_896_NON_ACTION_PAIR_RESOLUTION_TRACE.jsonl.gz")}\n- Exact event ledger: ${url("POPULATION_EVENT_LEDGER.jsonl.gz")}\n- Exact leg ledger: ${url("POPULATION_LEG_LEDGER.jsonl.gz")}\n- Mutual narrowing receipt: ${url("MUTUAL_NARROWING_RECEIPT.json")}\n- Determinism: ${url("DETERMINISM_RECEIPT.json")}\n\nPair hypothesis membership is fitted only from synchronized interim quote trajectories. Descents are inspected afterward only to certify coherence. No price region, cell, bucket, endpoint label, forecast, fee test, scorer, holdout, or live surface participates. This is in-sample development evidence, not a holdout result or market ceiling.\n`);
  const sources = [fit1, path.join(out, "POPULATION_EVENT_LEDGER.jsonl.gz"), v11LegPath, v11EventPath, v11FunnelPath, v11CarriedPath, path.join(repo, "arb-executor/analysis/build_window1_pair_interim_library_v18.js"), path.join(repo, "arb-executor/analysis/window1_pair_interim_elimination_v18.js"), path.join(repo, "arb-executor/analysis/build_window1_quote_shape_elimination_replay_v1.js"), path.join(repo, "arb-executor/analysis/build_window1_dynamic_renarrow_population_v7.js"), __filename]; fs.writeFileSync(path.join(out, "SOURCE_HASH_MANIFEST.json"), canonical({ files: Object.fromEntries(sources.map((file) => [rel(file), { sha256: hashFile(file), bytes: fs.statSync(file).size }])) }));
  const artifactNames = fs.readdirSync(out).filter((name) => name !== "ARTIFACT_HASH_MANIFEST.json").sort(); fs.writeFileSync(path.join(out, "ARTIFACT_HASH_MANIFEST.json"), canonical({ files: Object.fromEntries(artifactNames.map((name) => [name, { sha256: hashFile(path.join(out, name)), bytes: fs.statSync(path.join(out, name)).size }])) }));
  process.stdout.write(canonical({ status: "BUILT", output: rel(out), pair_census: library.census, comparison, non_action: nonAction }));
}
main();
