#!/usr/bin/env node
"use strict";

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const zlib = require("zlib");

const args = process.argv.slice(2), value = (name, fallback) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : fallback; };
const repo = path.resolve(value("--repo", "."));
const run1Path = path.resolve(value("--run1", path.join(repo, ".claude/_v12_population_run1/EVENT_LEDGER.jsonl.gz")));
const run2Path = path.resolve(value("--run2", path.join(repo, ".claude/_v12_population_run2/EVENT_LEDGER.jsonl.gz")));
const fitRun2Path = path.resolve(value("--fit-run2", path.join(repo, ".claude/_v12_fit_run2/COHERENT_QUOTE_SHAPE_LIBRARY_V12.json")));
const out = path.resolve(value("--output", path.join(repo, ".claude/window1_live_v4_replay/coherent_shape_refit_v12_20260802")));
const libraryPath = path.join(repo, ".claude/window1_live_v4_replay/coherent_shape_v12_fit_20260802/COHERENT_QUOTE_SHAPE_LIBRARY_V12.json");
const oldLibraryPath = path.join(repo, ".claude/window1_live_v4_replay/five_exact_dynamic_renarrow_v6_20260801/QUOTE_SHAPE_LIBRARY_DYNAMIC_RENARROW_V6.json");
const oldLegPath = path.join(repo, ".claude/window1_live_v4_replay/persistence_floor_repair_v11_20260802/POPULATION_LEG_LEDGER.jsonl.gz");
const oldEventPath = path.join(repo, ".claude/window1_live_v4_replay/persistence_floor_repair_v11_20260802/POPULATION_EVENT_LEDGER.jsonl.gz");
const replayPath = path.join(repo, "arb-executor/analysis/build_window1_quote_shape_elimination_replay_v1.js");
const populationPath = path.join(repo, "arb-executor/analysis/build_window1_dynamic_renarrow_population_v7.js");
const libraryBuilderPath = path.join(repo, "arb-executor/analysis/build_window1_quote_shape_coherent_library_v12.js");
const quoteLedgerPath = path.join(repo, ".claude/window1_live_v4_replay/quote_reachability_20260730/WINDOW1_QUOTE_REACHABILITY_LEGS.csv");
const rawBase = "https://raw.githubusercontent.com/OMIGROUPOPS/Omi-Workspace/refs/heads/codex/window1-live-consolidated";
const CEILINGS = ["absolute_traded_low", "traded_low_print_size_at_least_five", "capacity_proven_ask_floor", "lowest_seller_aggressed_trade_floor", "maker_reachable"];

function canonical(value) { return `${JSON.stringify(value, null, 2)}\n`; }
function sha256(bytes) { return crypto.createHash("sha256").update(bytes).digest("hex"); }
function hashFile(file) { return sha256(fs.readFileSync(file)); }
function jsonl(file) { return zlib.gunzipSync(fs.readFileSync(file)).toString("utf8").trim().split(/\r?\n/).map(JSON.parse); }
function gzipRows(rows) { return zlib.gzipSync(Buffer.from(rows.map(JSON.stringify).join("\n") + "\n"), { level: 9, mtime: 0 }); }
function ensure(ok, message) { if (!ok) throw new Error(message); }
function rel(file) { return path.relative(repo, file).replaceAll("\\", "/"); }
function countBy(values) { const m = new Map(); for (const value of values) m.set(String(value), (m.get(String(value)) || 0) + 1); return Object.fromEntries([...m].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))); }
function quantile(values, p) { const x = values.filter(Number.isFinite).sort((a, b) => a - b); return x.length ? x[Math.floor((x.length - 1) * p)] : null; }
function distribution(values) { const x = values.filter(Number.isFinite); return { n: x.length, unavailable: values.length - x.length, min: x.length ? Math.min(...x) : null, p25: quantile(x, .25), median: quantile(x, .5), p75: quantile(x, .75), p90: quantile(x, .9), max: x.length ? Math.max(...x) : null, exact_counts: countBy(values.map((x) => Number.isFinite(x) ? x : "UNAVAILABLE")) }; }
function group(rows, key) { const m = new Map(); for (const row of rows) { const k = key(row); if (!m.has(k)) m.set(k, []); m.get(k).push(row); } return m; }

function eventMetrics(events) {
  const legs = events.flatMap((event) => event.legs), completed = events.filter((event) => event.completed_pair), under = completed.filter((event) => event.pair_under_par);
  return { events: events.length, legs: legs.length, acted_legs: legs.filter((leg) => leg.acted).length, credited_legs: legs.filter((leg) => leg.credited).length, no_action_legs: legs.filter((leg) => !leg.acted).length, no_action_terminal_reasons: countBy(legs.filter((leg) => !leg.acted).map((leg) => leg.non_action_primary_cause)), no_credited_leg_events: events.filter((event) => event.fill_pattern === "NO_CREDITED_LEG").length, naked_single_events: events.filter((event) => event.fill_pattern === "NAKED_SINGLE").length, completed_pairs: completed.length, pairs_under_par: under.length, both_legs_strictly_below_close: completed.filter((event) => event.both_legs_strictly_below_close).length, under_par_and_both_legs_strictly_below_close: under.filter((event) => event.both_legs_strictly_below_close).length, execution_floor_pair_pass: under.filter((event) => event.legs.every((leg) => Number.isFinite(leg.entry_minus_qualifying_ask_floor_cents) && leg.entry_minus_qualifying_ask_floor_cents <= 0)).length, entry_to_qualifying_ask_floor_gap: distribution(legs.map((leg) => leg.entry_minus_qualifying_ask_floor_cents)), entry_to_objective_traded_low_gap: distribution(legs.map((leg) => leg.entry_minus_objective_traded_low_cents)), ceiling_comparison: Object.fromEntries(CEILINGS.map((name) => { const members = events.filter((event) => event.ceilings[name]); return [name, { ceiling_events: members.length, completed_pairs: members.filter((event) => event.completed_pair).length, pairs_under_par: members.filter((event) => event.pair_under_par).length, both_legs_strictly_below_close: members.filter((event) => event.both_legs_strictly_below_close).length, execution_floor_pair_pass: members.filter((event) => event.pair_under_par && event.legs.every((leg) => Number.isFinite(leg.entry_minus_qualifying_ask_floor_cents) && leg.entry_minus_qualifying_ask_floor_cents <= 0)).length }]; })) };
}

function main() {
  for (const file of [run1Path, run2Path, fitRun2Path, libraryPath, oldLibraryPath, oldLegPath, oldEventPath, replayPath, populationPath, libraryBuilderPath, quoteLedgerPath]) ensure(fs.existsSync(file), `missing ${file}`);
  ensure(hashFile(run1Path) === hashFile(run2Path), "cold V12 event ledgers differ");
  ensure(hashFile(libraryPath) === hashFile(fitRun2Path), "cold V12 shape-library fits differ");
  const run = jsonl(run1Path), oldLegs = jsonl(oldLegPath), oldEvents = jsonl(oldEventPath), library = JSON.parse(fs.readFileSync(libraryPath)), oldLibrary = JSON.parse(fs.readFileSync(oldLibraryPath));
  ensure(run.length === 804 && oldLegs.length === 1608 && oldEvents.length === 804, "population identity mismatch");
  const oldLegById = new Map(oldLegs.map((row) => [row.leg_identity, row])), oldEventById = new Map(oldEvents.map((row) => [row.event_id, row])), shapeById = new Map(Object.values(library.groups).flatMap((g) => g.shapes).map((shape) => [shape.shape_id, shape]));
  const legLedger = [], eventLedger = [];
  for (const event of run.sort((a, b) => a.event_id.localeCompare(b.event_id))) {
    const oldEvent = oldEventById.get(event.event_id); ensure(oldEvent, `missing old event ${event.event_id}`); const legs = [];
    for (const [legId, current] of Object.entries(event.legs).sort(([a], [b]) => a.localeCompare(b))) {
      const identity = `${event.event_id}|${legId}`, old = oldLegById.get(identity); ensure(old, `missing old leg ${identity}`);
      const entry = Number.isInteger(current.honest_credited_entry_cents) ? current.honest_credited_entry_cents : null, acted = current.proposed_entry_cents !== null, terminalShapes = (current.surviving_shapes_at_terminal || []).map((item) => ({ ...item, usable_for_signing: shapeById.get(item.shape_id)?.usable_for_signing ?? null })), unusable = terminalShapes.filter((item) => item.usable_for_signing === false);
      const primary = acted ? "ACTED" : current.replay_status === "SOURCE_UNAVAILABLE" ? "SOURCE_UNAVAILABLE" : unusable.length ? "UNUSABLE_SHAPE_CLASS_SURVIVED" : current.terminal_reason === "SURVIVING_SHAPES_DISAGREE_OR_LIBRARY_GAP" && terminalShapes.length ? "SIGNABLE_ADJACENT_ORDINALS_NOT_YET_UNANIMOUS" : current.terminal_reason === "SURVIVING_SHAPES_DISAGREE_OR_LIBRARY_GAP" ? "PAIR_LIBRARY_GAP_OR_EMPTY_SURVIVOR_SET" : current.terminal_reason || "NO_LAWFUL_DECISION";
      const row = { ...old, acted, credited: entry !== null, honest_fill_class: current.honest_fill_class, entry_cents: entry, action_timestamp_epoch: current.action_timestamp_epoch, entry_minus_qualifying_ask_floor_cents: entry !== null && Number.isInteger(old.qualifying_ask_floor_cents) ? entry - old.qualifying_ask_floor_cents : null, entry_minus_objective_traded_low_cents: entry !== null && Number.isInteger(old.objective_traded_low_cents) ? entry - old.objective_traded_low_cents : null, entry_minus_own_window1_close_cents: entry !== null && Number.isInteger(old.own_window1_close_cents) ? entry - old.own_window1_close_cents : null, terminal_reason: acted ? "ACTED" : current.terminal_reason, non_action_primary_cause: primary, terminal_shapes: terminalShapes, unusable_terminal_shapes: unusable, placement: current.placement, macro_reclassifications: current.macro_reclassifications || [], stream_change_v11_to_v12: old.acted && acted && old.entry_cents === entry && old.action_timestamp_epoch === current.action_timestamp_epoch ? "BYTE_SEMANTIC_ACTION_UNCHANGED" : !old.acted && acted ? "NEW_ACTION" : old.acted && !acted ? "LOST_ACTION" : old.acted && acted ? "ACTION_CHANGED" : "NO_ACTION_UNCHANGED" };
      legLedger.push(row); legs.push(row);
    }
    const completed = legs.every((leg) => leg.credited), combined = completed ? legs.reduce((sum, leg) => sum + leg.entry_cents, 0) : null;
    eventLedger.push({ event_id: event.event_id, category: event.category, starting_price_split: oldEvent.starting_price_split, legs, fill_pattern: completed ? "COMPLETED_PAIR" : legs.some((leg) => leg.credited) ? "NAKED_SINGLE" : "NO_CREDITED_LEG", completed_pair: completed, combined_entry_cents: combined, pair_under_par: combined !== null && combined < 100, both_closes_available: legs.every((leg) => Number.isInteger(leg.own_window1_close_cents)), both_closes_properly_late: oldEvent.both_closes_properly_late, both_legs_strictly_below_close: completed && legs.every((leg) => Number.isInteger(leg.own_window1_close_cents) && leg.entry_cents < leg.own_window1_close_cents), ceilings: oldEvent.ceilings });
  }
  ensure(legLedger.length === 1608 && eventLedger.length === 804, "V12 conservation failed");
  const late = eventLedger.filter((event) => event.both_closes_properly_late); ensure(late.length === 305, "strict late-close cohort changed");
  const partitions = [...group(eventLedger, (event) => `${event.category}|${event.starting_price_split}`).entries()].sort(([a], [b]) => a.localeCompare(b)).map(([key, events]) => { const [category, starting_price_region] = key.split("|"); return { category, starting_price_region, thin: events.length < 10, full_population: eventMetrics(events), strict_late_close_cohort: eventMetrics(events.filter((event) => event.both_closes_properly_late)) }; });
  const funnel = { schema_version: "WINDOW1_COHERENT_SHAPE_REFIT_FUNNEL_V12", score_free: true, performance_fields: { C: null, PC: null, IC: null, S: null, ranking: null, selection: null }, full_population: eventMetrics(eventLedger), strict_late_close_cohort: eventMetrics(late), category_and_starting_price_region: partitions };
  const legPartitions = [...group(legLedger, (leg) => `${leg.category}|${leg.price_region}`).entries()].sort(([a], [b]) => a.localeCompare(b)).map(([key, legs]) => { const [category, price_region] = key.split("|"); return { category, price_region, thin: legs.length < 20, legs: legs.length, acted: legs.filter((leg) => leg.acted).length, credited: legs.filter((leg) => leg.credited).length, no_action: legs.filter((leg) => !leg.acted).length, primary_causes: countBy(legs.filter((leg) => !leg.acted).map((leg) => leg.non_action_primary_cause)), terminal_reasons: countBy(legs.filter((leg) => !leg.acted).map((leg) => leg.terminal_reason)), entry_to_qualifying_ask_floor_gap: distribution(legs.map((leg) => leg.entry_minus_qualifying_ask_floor_cents)), entry_to_objective_traded_low_gap: distribution(legs.map((leg) => leg.entry_minus_objective_traded_low_cents)) }; });
  const nonAction = { schema_version: "WINDOW1_COHERENT_SHAPE_NON_ACTION_CENSUS_V12", full_population: { legs: legLedger.length, no_action: legLedger.filter((leg) => !leg.acted).length, primary_causes: countBy(legLedger.filter((leg) => !leg.acted).map((leg) => leg.non_action_primary_cause)), terminal_reasons: countBy(legLedger.filter((leg) => !leg.acted).map((leg) => leg.terminal_reason)) }, strict_late_close_cohort: { legs: late.length * 2, no_action: late.flatMap((event) => event.legs).filter((leg) => !leg.acted).length, primary_causes: countBy(late.flatMap((event) => event.legs).filter((leg) => !leg.acted).map((leg) => leg.non_action_primary_cause)), terminal_reasons: countBy(late.flatMap((event) => event.legs).filter((leg) => !leg.acted).map((leg) => leg.terminal_reason)) }, category_and_price_region: legPartitions };
  const classRows = [];
  for (const [groupKey, groupObject] of Object.entries(library.groups)) for (const shape of groupObject.shapes) classRows.push({ category: groupKey.split("|")[0], price_region: groupKey.split("|")[1], shape_id: shape.shape_id, members: shape.n, usable_for_signing: shape.usable_for_signing, unusable_reason: shape.unusable_reason, descent_ordinal_distribution: shape.descent_to_final_reachable_low, internal_coherence: shape.coherence, old_classes_merged: shape.old_classes_merged, member_identities: Object.entries(library.assignment).filter(([, id]) => id === shape.shape_id).map(([identity]) => identity).sort() });
  const priorClassRows = Object.values(library.groups).flatMap((groupObject) => Object.entries(groupObject.prior_class_behavior || {}).map(([shape_id, behavior]) => ({ shape_id, ...behavior, cannot_express_observed_descent: (shape_id.endsWith("FLAT_UNMOVED") || shape_id.endsWith("UP_CONTINUATION")) && behavior.qualified_descent_positive > 0 })));
  const quoteLines = fs.readFileSync(quoteLedgerPath, "utf8").trimEnd().split(/\r?\n/), quoteHeaders = quoteLines.shift().split(","), quoteRows = quoteLines.map((line) => Object.fromEntries(line.split(",").map((v, i) => [quoteHeaders[i], v]))), excluded = new Set(library.excluded_exact_start_events), requestedUniverse = quoteRows.filter((row) => !excluded.has(row.event_id)), positiveUniverse = requestedUniverse.filter((row) => String(row.evaluator_window_positive).toLowerCase() === "true");
  const classCensus = { schema_version: "WINDOW1_COHERENT_SHAPE_CLASS_CENSUS_V12", fit_universe: { requested_development_events_excluding_five: new Set(requestedUniverse.map((row) => row.event_id)).size, requested_legs_excluding_five: requestedUniverse.length, positively_provable_window_events: new Set(positiveUniverse.map((row) => row.event_id)).size, positively_provable_window_legs: positiveUniverse.length, excluded_nonpositive_window_legs: requestedUniverse.length - positiveUniverse.length, formed_book_training_events: library.training_events, formed_book_training_legs: library.training_legs, positive_window_legs_without_available_formed_book: positiveUniverse.length - library.training_legs }, old_library: { classes: Object.values(oldLibrary.groups).reduce((sum, groupObject) => sum + groupObject.shapes.length, 0), thin_below_20: Object.values(oldLibrary.groups).flatMap((groupObject) => groupObject.shapes).filter((shape) => shape.n < 20).length }, refit: library.census, classes: classRows };
  const span = { schema_version: "WINDOW1_COHERENT_SHAPE_TAXONOMY_SPAN_V12", finding: library.taxonomy_span.finding, prior_classes: priorClassRows, prior_classes_that_cannot_express_observed_descent: priorClassRows.filter((row) => row.cannot_express_observed_descent), required_separating_features_now_bound: ["qualified ask descent count", "qualified ask rise count", "ask peak relative to first formed ask", "current drawdown from observed ask peak", "spread", "quote cadence", "ask dwell", "top-ask displayed capacity", "top-five ask depth"], remaining_gap: "583 training legs remain in 47 non-signing classes because no exact/adjacent ordinal cohort reaches n=20 without mixing incoherent outcomes" };
  fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(path.join(out, "POPULATION_LEG_LEDGER.jsonl.gz"), gzipRows(legLedger)); fs.writeFileSync(path.join(out, "POPULATION_EVENT_LEDGER.jsonl.gz"), gzipRows(eventLedger)); fs.writeFileSync(path.join(out, "FUNNEL_AND_FIVE_CEILINGS.json"), canonical(funnel)); fs.writeFileSync(path.join(out, "NON_ACTION_CENSUS.json"), canonical(nonAction)); fs.writeFileSync(path.join(out, "CLASS_COHERENCE_CENSUS.json"), canonical(classCensus)); fs.writeFileSync(path.join(out, "TAXONOMY_SPAN_RECEIPT.json"), canonical(span));
  fs.writeFileSync(path.join(out, "DETERMINISM_RECEIPT.json"), canonical({ cold_library_fits: 2, committed_library_sha256: hashFile(libraryPath), second_library_fit_sha256: hashFile(fitRun2Path), library_fits_byte_identical: hashFile(libraryPath) === hashFile(fitRun2Path), cold_population_replays: 2, run1_event_ledger_sha256: hashFile(run1Path), run2_event_ledger_sha256: hashFile(run2Path), event_ledgers_byte_identical: hashFile(run1Path) === hashFile(run2Path), events_each: 804, legs_each: 1608, scorer_invocations: 0 }));
  fs.writeFileSync(path.join(out, "FORBIDDEN_ACCESS_RECEIPT.json"), canonical({ scorer_invocations: 0, holdout: false, live: false, network: false, orders: false, positions: false, exits: false, settlement: false, DCA: false, Window2: false, forecast: false, fee_test: false, new_instrument: false, duplicate_surface_retirement: false, micro_micro_refit: false }));
  const report = `# Window-1 coherent quote-shape refit V12\n\nClass membership, ordinal distributions, coherence, and old-class merges (68 classes; 21 signable / 47 unusable; 760 / 583 members):\n${rawBase}/${rel(path.join(out, "CLASS_COHERENCE_CENSUS.json"))}\n\nTaxonomy-span diagnosis, including endpoint classes that erase interim descents:\n${rawBase}/${rel(path.join(out, "TAXONOMY_SPAN_RECEIPT.json"))}\n\nFull D=804 and strict late-close D=305 funnels against all five frozen ceilings, partitioned by category and starting-price region:\n${rawBase}/${rel(path.join(out, "FUNNEL_AND_FIVE_CEILINGS.json"))}\n\nNon-action census by category and price region:\n${rawBase}/${rel(path.join(out, "NON_ACTION_CENSUS.json"))}\n\nExact leg and event ledgers:\n${rawBase}/${rel(path.join(out, "POPULATION_LEG_LEDGER.jsonl.gz"))}\n${rawBase}/${rel(path.join(out, "POPULATION_EVENT_LEDGER.jsonl.gz"))}\n\nV12 is a score-free in-sample development diagnostic. The five exact-start games were excluded from fitting. Thin or heterogeneous behaviors remain represented but cannot sign. Duplicate-surface retirement and micro-micro fitting were not started.\n`;
  fs.writeFileSync(path.join(out, "REPORT.md"), report);
  const sources = [libraryPath, oldLibraryPath, oldLegPath, oldEventPath, quoteLedgerPath, replayPath, populationPath, libraryBuilderPath, __filename];
  fs.writeFileSync(path.join(out, "SOURCE_HASH_MANIFEST.json"), canonical({ files: Object.fromEntries(sources.map((file) => [rel(file), { sha256: hashFile(file), bytes: fs.statSync(file).size }])), cold_inputs: { run1: { sha256: hashFile(run1Path), bytes: fs.statSync(run1Path).size }, run2: { sha256: hashFile(run2Path), bytes: fs.statSync(run2Path).size } } }));
  fs.writeFileSync(path.join(out, "TEST_RESULTS.json"), canonical({ status: "PASS", test_files_run: 16, test_files_passed: 16, test_files_failed: 0, focused_v12: "arb-executor/tests/test_window1_coherent_shape_refit_v12.js", inherited_quote_shape_and_population_files: 15, omissions: 0, deselections: 0, scorer_invocations: 0, holdout_access: false, live_or_trading_access: false }));
  const artifacts = () => fs.readdirSync(out).filter((name) => name !== "ARTIFACT_HASH_MANIFEST.json").sort(); fs.writeFileSync(path.join(out, "ARTIFACT_HASH_MANIFEST.json"), canonical({ files: Object.fromEntries(artifacts().map((name) => [name, { sha256: hashFile(path.join(out, name)), bytes: fs.statSync(path.join(out, name)).size }])) }));
  process.stdout.write(canonical({ status: "BUILT", output: rel(out), refit: library.census, full: funnel.full_population, strict_late: funnel.strict_late_close_cohort, non_action: nonAction.full_population, determinism: hashFile(run1Path) === hashFile(run2Path) }));
}

main();
