import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {makePolicy,validateDeterminism,LABEL,RUN_ROOT} from './tune_policy.mjs';
const bytes=fs.readFileSync(RUN_ROOT+'/SELECTION.json'),selection=JSON.parse(bytes),hash=crypto.createHash('sha256').update(bytes).digest('hex');
const a=makePolicy(selection,hash),b=makePolicy({...selection,selected:[...selection.selected].reverse()},hash);
assert.deepEqual(a,b);assert.equal(a.sample_events.length,10);assert.equal(new Set(a.sample_events).size,10);
assert(a.sample_events.includes('KXATPMATCH-26JUL12ALTGAS'));assert(a.sample_events.includes('KXATPCHALLENGERMATCH-26JUL14GANZIN'));
assert.equal(a.sample_events.filter(e=>selection.selected.some(r=>r.event_id===e)).length,9);
const sample=a.sample_events[0],other=selection.selected.find(r=>!a.sample_events.includes(r.event_id)).event_id;
const one=event=>({event,first:{sha256:'fixture',bytes:1,counts:{}},second:null,passes:1,all_byte_identical:null});
assert.doesNotThrow(()=>validateDeterminism(one(other),other,a));
assert.throws(()=>validateDeterminism(one(sample),sample,a));
assert.doesNotThrow(()=>validateDeterminism(one(sample),sample,a,{requireSample:false}));
const twice={...one(sample),second:one(sample).first,passes:2,all_byte_identical:true};
assert.doesNotThrow(()=>validateDeterminism(twice,sample,a));
assert.throws(()=>validateDeterminism({...twice,second:{sha256:'different'}},sample,a));
assert.throws(()=>validateDeterminism({...one(other),all_byte_identical:true},other,a));
assert.equal(a.label,LABEL);console.log(JSON.stringify({status:'PASS',label:LABEL,sample:a.sample_events}));
